/**
 * Wave 2.15a — top 5 high-impact Cost Q&A × 7 locales × 2 fields = 70 strings.
 * These are the most-search-clicked patient questions; closes the highest-leverage
 * Q&A translation gaps. 126 long-tail Q&A entries remain for future sessions
 * (Waves 2.15b/c) — total work ~756k chars, infeasible in a single session.
 */
import { db } from "../src/lib/db";
import { sql } from "drizzle-orm";

type Locale = "ar" | "bn" | "fr" | "hi" | "pt" | "ru" | "tr";
const LOCALES: Locale[] = ["ar", "bn", "fr", "hi", "pt", "ru", "tr"];

interface Q { id: number; q: Record<Locale, string>; a: Record<Locale, string>; }

const QAS: Q[] = [
  { id: 1,
    q: { ar: "كم تكلفة جراحة CABG (مجازة القلب) في الهند؟", bn: "ভারতে CABG (হার্ট বাইপাস) এর খরচ কত?", fr: "Combien coûte un CABG (pontage coronarien) en Inde ?", hi: "भारत में CABG (हृदय बाईपास) की लागत कितनी है?", pt: "Quanto custa um CABG (ponte de safena) na Índia?", ru: "Сколько стоит АКШ (аортокоронарное шунтирование) в Индии?", tr: "Hindistan'da CABG (kalp bypass) ne kadara mal olur?" },
    a: { ar: "تتراوح جراحة المجازة (CABG) في الهند عادةً بين 3,800$ و8,500$ في مستشفيات الفئة الأولى (Medanta وApollo وFortis وMax). هذا أقل بنسبة 85-95% من عرض مماثل في الولايات المتحدة (70,000$-120,000$). يجب أن يفصّل العرض: أتعاب الجراح والتخدير، أيام غرفة العمليات والعناية المركزة، الإقامة في الجناح (6-8 ليالٍ عادةً)، الأدوية القياسية، والمتابعة الأولى. ما يجب الانتباه إليه: ماركة الزرعة إذا كانت الصمامات معنية (Edwards Lifesciences مقابل العام له فرق فعلي)، ضمان جراحة المراجعة، وما يشمله المتابعة في أول 30 يومًا. أضف 1,000$-2,500$ للرحلات وإقامة التعافي.",
      bn: "ভারতে হার্ট বাইপাস (CABG) সাধারণত টিয়ার-১ হাসপাতালে (Medanta, Apollo, Fortis, Max) $৩,৮০০ থেকে $৮,৫০০ পর্যন্ত। এটি US-এ তুলনাযোগ্য কোটেশনের ($৭০,০০০-$১,২০,০০০) চেয়ে ৮৫-৯৫% কম। কোটে আইটেমাইজ করা উচিত: সার্জন + অ্যানেস্থেসিয়া ফি, OR + ICU দিন, ওয়ার্ড স্টে (সাধারণত ৬-৮ রাত), স্ট্যান্ডার্ড ওষুধ, এবং প্রথম ফলো-আপ। সতর্ক থাকার বিষয়: ভাল্ভ জড়িত থাকলে ইমপ্লান্ট ব্র্যান্ড (Edwards Lifesciences বনাম জেনেরিকের প্রকৃত পার্থক্য আছে), রিভিশন সার্জারি ওয়ারেন্টি, এবং ৩০-দিনের ফলো-আপে কী অন্তর্ভুক্ত। ফ্লাইট এবং পুনরুদ্ধার বাসস্থানের জন্য $১,০০০-২,৫০০ যোগ করুন।",
      fr: "Le pontage coronarien (CABG) en Inde se situe généralement entre 3 800 $ et 8 500 $ dans les hôpitaux de premier rang (Medanta, Apollo, Fortis, Max). C’est 85 à 95 % de moins qu’un devis comparable aux États-Unis (70 000–120 000 $). Le devis doit détailler : honoraires du chirurgien et de l’anesthésie, jours en bloc et en réa, séjour en chambre (6–8 nuits typique), médicaments standards, et premier contrôle. Points de vigilance : marque de l’implant si valves concernées (Edwards Lifesciences vs générique a un vrai impact), garantie de chirurgie de révision, et ce qui est inclus dans le suivi à 30 jours. Ajoutez 1 000–2 500 $ pour les vols et l’hébergement de récupération.",
      hi: "भारत में हार्ट बाईपास (CABG) आमतौर पर टियर-1 अस्पतालों (Medanta, Apollo, Fortis, Max) में $3,800 से $8,500 तक होता है। यह US में तुलनीय कोट ($70,000-$120,000) से 85-95% कम है। कोट में आइटमाइज़ करना चाहिए: सर्जन + एनेस्थीसिया फीस, OR + ICU दिन, वार्ड स्टे (आमतौर पर 6-8 रातें), मानक दवाएँ, और पहली फॉलो-अप। ध्यान देने वाली बातें: यदि वाल्व शामिल हैं तो इम्प्लांट ब्रांड (Edwards Lifesciences बनाम जेनेरिक में वास्तविक अंतर है), रिविज़न सर्जरी वारंटी, और 30-दिन के फॉलो-अप में क्या शामिल है। उड़ानों और रिकवरी आवास के लिए $1,000-2,500 जोड़ें।",
      pt: "O pontes de safena (CABG) na Índia geralmente custa entre $3.800 e $8.500 em hospitais de primeira linha (Medanta, Apollo, Fortis, Max). Isso é 85-95% menos que um orçamento comparável nos EUA ($70.000-$120.000). O orçamento deve detalhar: honorários do cirurgião e anestesia, dias em centro cirúrgico e UTI, internação em ala (6-8 noites típicas), medicações padrão, e primeiro retorno. O que observar: marca do implante se válvulas envolvidas (Edwards Lifesciences vs genérico tem diferença real), garantia de cirurgia de revisão, e o que está incluído no seguimento de 30 dias. Adicione $1.000-2.500 para voos e hospedagem de recuperação.",
      ru: "Аортокоронарное шунтирование (АКШ) в Индии обычно стоит от 3 800 до 8 500 $ в клиниках первого уровня (Medanta, Apollo, Fortis, Max). Это на 85-95% меньше, чем сопоставимое предложение в США (70 000-120 000 $). В смете должны быть указаны: гонорар хирурга и анестезии, дни в операционной и ОРИТ, пребывание в палате (типично 6-8 ночей), стандартные лекарства, первый осмотр. На что обратить внимание: марка импланта при операциях с клапанами (Edwards Lifesciences vs генерик дают реальную разницу), гарантия на ревизионную операцию, и что включено в 30-дневное наблюдение. Добавьте 1 000-2 500 $ на перелёты и жильё для восстановления.",
      tr: "Hindistan'da kalp bypass (CABG) genellikle birinci sınıf hastanelerde (Medanta, Apollo, Fortis, Max) $3.800 ile $8.500 arasındadır. Bu, ABD'deki karşılaştırılabilir teklifin ($70.000-$120.000) %85-95 altındadır. Teklifin detaylandırması gereken: cerrah + anestezi ücreti, ameliyathane + yoğun bakım günleri, koğuş yatışı (tipik 6-8 gece), standart ilaçlar ve ilk kontrol. Dikkat edilecekler: kapaklar dahilse implant markası (Edwards Lifesciences vs jenerik gerçek bir fark yaratır), revizyon cerrahi garantisi ve 30 günlük takipte neler dahil. Uçuşlar ve iyileşme konaklaması için $1.000-2.500 ekleyin." }
  },
  { id: 50,
    q: { ar: "هل علاج السرطان أرخص في الهند مقارنة بالولايات المتحدة؟", bn: "ক্যান্সার চিকিৎসা কি ভারতে US-এর চেয়ে সস্তা?", fr: "Le traitement du cancer est-il moins cher en Inde qu’aux États-Unis ?", hi: "क्या भारत में कैंसर उपचार US से सस्ता है?", pt: "O tratamento de câncer é mais barato na Índia que nos EUA?", ru: "Лечение рака в Индии дешевле, чем в США?", tr: "Kanser tedavisi Hindistan'da ABD'den daha mı ucuz?" },
    a: { ar: "نعم، عادةً أقل بنسبة 70-85% للنظام نفسه. يفسّر تصنيع الأدوية الجنيسة والمماثلة الحيوية معظم الفجوة. الجراحة الأورامية والإشعاع والرعاية الداعمة أرخص أيضًا بشكل كبير. أمثلة حقيقية: نظام FOLFOX من 6 دورات لسرطان القولون يكلّف ~3-5 آلاف $ في الهند مقابل 30-60 ألف $ في الولايات المتحدة. سنة من ترستوزوماب (Herceptin) لسرطان الثدي تكلّف ~8-12 ألف $ في الهند مقابل 80-100 ألف $+ في الولايات المتحدة. جراحة سرطان شاملة (مثلًا ويبل) تكلّف ~10-15 ألف $ في الهند مقابل 80-150 ألف $ في الولايات المتحدة. الجودة في أفضل مراكز السرطان الهندية (Tata Memorial، HCG، Apollo، Max) مماثلة للبرامج الأمريكية في الجراحة وعلم الأورام الطبي. حيث الهند أحيانًا أرق: الوصول إلى التجارب السريرية، علم الأورام الدقيق المتطور، العلاج المناعي الحديث.",
      bn: "হ্যাঁ, সাধারণত একই রেজিমেনের জন্য ৭০-৮৫% কম। জেনেরিক ও বায়োসিমিলার ওষুধ উৎপাদন ব্যবধানের অধিকাংশ কারণ। সার্জিকাল অনকোলজি, রেডিয়েশন এবং সহায়ক যত্নও উল্লেখযোগ্যভাবে সস্তা। বাস্তব উদাহরণ: কোলন ক্যান্সারের জন্য ৬-সাইকেল FOLFOX রেজিমেন ভারতে ~$৩-৫k বনাম US-এ $৩০-৬০k। স্তন ক্যান্সারের জন্য এক বছরের trastuzumab (Herceptin) ভারতে ~$৮-১২k বনাম US-এ $৮০-১০০k+। ব্যাপক ক্যান্সার সার্জারি (যেমন Whipple) ভারতে ~$১০-১৫k বনাম US-এ $৮০-১৫০k। শীর্ষ ভারতীয় ক্যান্সার কেন্দ্রে (Tata Memorial, HCG, Apollo, Max) গুণমান সার্জিকাল ও মেডিকেল অনকোলজিতে US প্রোগ্রামের সাথে তুলনীয়। যেখানে ভারত কখনো পাতলা: ক্লিনিকাল ট্রায়াল অ্যাক্সেস, অগ্রণী নির্ভুল অনকোলজি, নভেল ইমিউনোথেরাপি।",
      fr: "Oui, généralement 70 à 85 % moins cher pour le même protocole. La fabrication de médicaments génériques et biosimilaires explique l’essentiel de l’écart. La chirurgie oncologique, la radiothérapie et les soins de support sont également beaucoup moins chers. Exemples réels : un protocole FOLFOX de 6 cycles pour cancer colique coûte ~3 à 5 k$ en Inde vs 30 à 60 k$ aux États-Unis. Une année de trastuzumab (Herceptin) pour cancer du sein coûte ~8 à 12 k$ en Inde vs 80 à 100 k$+ aux États-Unis. Une chirurgie oncologique complète (ex. Whipple) coûte ~10 à 15 k$ en Inde vs 80 à 150 k$ aux États-Unis. La qualité des meilleurs centres oncologiques indiens (Tata Memorial, HCG, Apollo, Max) est comparable aux programmes américains en oncologie chirurgicale et médicale. Où l’Inde est parfois plus mince : accès aux essais cliniques, oncologie de précision de pointe, immunothérapie nouvelle.",
      hi: "हाँ, समान आहार के लिए आमतौर पर 70-85% कम। जेनेरिक और बायोसिमिलर दवा निर्माण अधिकांश अंतर के लिए ज़िम्मेदार है। सर्जिकल ऑन्कोलॉजी, विकिरण, और सहायक देखभाल भी काफ़ी सस्ती है। वास्तविक उदाहरण: कोलन कैंसर के लिए 6-चक्र FOLFOX आहार भारत में ~$3-5k बनाम US में $30-60k। स्तन कैंसर के लिए एक साल का trastuzumab (Herceptin) भारत में ~$8-12k बनाम US में $80-100k+। व्यापक कैंसर सर्जरी (जैसे Whipple) भारत में ~$10-15k बनाम US में $80-150k। शीर्ष भारतीय कैंसर केंद्रों (Tata Memorial, HCG, Apollo, Max) में गुणवत्ता सर्जिकल और मेडिकल ऑन्कोलॉजी में US कार्यक्रमों के तुलनीय है। जहाँ भारत कभी-कभी पतला है: नैदानिक परीक्षण पहुँच, अग्रणी सटीक ऑन्कोलॉजी, नई इम्यूनोथेरेपी।",
      pt: "Sim, tipicamente 70-85% mais barato para o mesmo regime. A fabricação de medicamentos genéricos e biossimilares responde pela maior parte da diferença. Oncologia cirúrgica, radiação e cuidados de suporte também são significativamente mais baratos. Exemplos reais: regime FOLFOX de 6 ciclos para câncer de cólon custa ~$3-5k na Índia vs $30-60k EUA. Um ano de trastuzumab (Herceptin) para câncer de mama custa ~$8-12k na Índia vs $80-100k+ EUA. Cirurgia oncológica abrangente (ex. Whipple) custa ~$10-15k na Índia vs $80-150k EUA. A qualidade nos principais centros oncológicos indianos (Tata Memorial, HCG, Apollo, Max) é comparável a programas americanos em oncologia cirúrgica e médica. Onde a Índia é às vezes mais fraca: acesso a ensaios clínicos, oncologia de precisão de ponta, imunoterapia inovadora.",
      ru: "Да, обычно на 70-85% дешевле для того же режима. Производство генериков и биосимиляров объясняет большую часть разницы. Хирургическая онкология, лучевая терапия и поддерживающее лечение также значительно дешевле. Реальные примеры: 6-цикловый режим FOLFOX при раке толстой кишки стоит ~3-5 тыс. $ в Индии vs 30-60 тыс. $ в США. Год трастузумаба (Herceptin) при раке груди — ~8-12 тыс. $ в Индии vs 80-100 тыс. $+ в США. Сложная онкохирургия (например, Уиппл) — ~10-15 тыс. $ в Индии vs 80-150 тыс. $ в США. Качество в ведущих индийских онкоцентрах (Tata Memorial, HCG, Apollo, Max) сопоставимо с американскими программами в хирургической и медицинской онкологии. Где Индия иногда уступает: доступ к клиническим испытаниям, передовая прецизионная онкология, новая иммунотерапия.",
      tr: "Evet, aynı rejim için tipik olarak %70-85 daha ucuz. Jenerik ve biyobenzer ilaç üretimi farkın çoğunu açıklar. Cerrahi onkoloji, radyasyon ve destekleyici bakım da önemli ölçüde daha ucuzdur. Gerçek örnekler: kolon kanseri için 6-siklus FOLFOX rejimi Hindistan'da ~$3-5k vs ABD'de $30-60k. Meme kanseri için bir yıllık trastuzumab (Herceptin) Hindistan'da ~$8-12k vs ABD'de $80-100k+. Kapsamlı kanser cerrahisi (örn. Whipple) Hindistan'da ~$10-15k vs ABD'de $80-150k. En iyi Hint kanser merkezlerindeki (Tata Memorial, HCG, Apollo, Max) kalite cerrahi ve tıbbi onkolojide ABD programlarıyla karşılaştırılabilir. Hindistan'ın bazen daha zayıf olduğu yerler: klinik araştırma erişimi, öncü hassas onkoloji, yeni immünoterapi." }
  },
  { id: 57,
    q: { ar: "كم تكلفة استبدال الركبة في الهند؟", bn: "ভারতে হাঁটু প্রতিস্থাপনের খরচ কত?", fr: "Combien coûte une prothèse de genou en Inde ?", hi: "भारत में घुटना प्रत्यारोपण की लागत कितनी है?", pt: "Quanto custa uma prótese de joelho na Índia?", ru: "Сколько стоит эндопротезирование колена в Индии?", tr: "Hindistan'da diz protezi ne kadara mal olur?" },
    a: { ar: "استبدال الركبة الكامل يكلّف 4,500$-7,000$ في أفضل المراكز الهندية (Apollo، Fortis، Max). الثنائي المتزامن يكلّف 7,500$-10,500$. مساعدة روبوتية (MAKO) تضيف 1,500$-3,000$ على القاعدة. مشمول في الباقات القياسية: الجراحة، الزرعة، إقامة 3-5 أيام، علاج طبيعي أساسي، متابعة. مستثنى لكن عادةً مطلوب: علاج طبيعي ممتد (غالبًا 2-4 أسابيع في فندق التعافي)، خطة علاج طبيعي في البلد، أدوية ما بعد الخروج. لا تتفاجأ بأن الرقم الإجمالي أعلى بـ15-25% من سعر الباقة الرئيسي بمجرد إدراج الإقامة الممتدة والترانزيت والإقامة. التكلفة الإجمالية للرحلة: 7,000$-10,000$ للجانب الواحد، 10,500$-14,000$ للثنائي.",
      bn: "শীর্ষ ভারতীয় কেন্দ্রে (Apollo, Fortis, Max) সম্পূর্ণ হাঁটু প্রতিস্থাপন $৪,৫০০-৭,০০০। দ্বিপাক্ষিক একসাথে $৭,৫০০-১০,৫০০। রোবোটিক-অ্যাসিস্টেড (MAKO) বেসে $১,৫০০-৩,০০০ যোগ করে। স্ট্যান্ডার্ড প্যাকেজে অন্তর্ভুক্ত: সার্জারি, ইমপ্লান্ট, ৩-৫ দিন অবস্থান, বেসিক PT, ফলো-আপ। বাদ দেওয়া কিন্তু সাধারণত দরকার: বর্ধিত PT (প্রায়ই পুনরুদ্ধার হোটেলে ২-৪ সপ্তাহ), দেশের PT পরিকল্পনা, পোস্ট-ডিসচার্জ ওষুধ। বর্ধিত অবস্থান, ট্রানজিট ও বাসস্থান অন্তর্ভুক্ত করার পর সর্বমোট সংখ্যা হেডলাইন প্যাকেজ মূল্যের চেয়ে ১৫-২৫% বেশি হলে অবাক হবেন না। মোট ভ্রমণ খরচ: একপাক্ষিকের জন্য $৭,০০০-১০,০০০, দ্বিপাক্ষিকের জন্য $১০,৫০০-১৪,০০০।",
      fr: "La prothèse totale de genou coûte 4 500–7 000 $ dans les meilleurs centres indiens (Apollo, Fortis, Max). Bilatérale simultanée coûte 7 500–10 500 $. Assistée par robot (MAKO) ajoute 1 500–3 000 $ à la base. Inclus dans les forfaits standards : chirurgie, implant, 3–5 jours de séjour, kinésithérapie de base, suivi. Exclus mais généralement nécessaires : kinésithérapie prolongée (souvent 2–4 semaines à l’hôtel de récupération), plan de kinésithérapie au pays d’origine, médicaments post-sortie. Ne soyez pas surpris que le total soit 15–25 % plus élevé que le prix forfait affiché une fois inclus séjour prolongé, transit et hébergement. Coût total du voyage : 7 000–10 000 $ pour unilatérale, 10 500–14 000 $ pour bilatérale.",
      hi: "शीर्ष भारतीय केंद्रों (Apollo, Fortis, Max) में पूर्ण घुटना प्रत्यारोपण $4,500-7,000 चलता है। द्विपक्षीय एक साथ $7,500-10,500 चलता है। रोबोटिक-असिस्टेड (MAKO) बेस पर $1,500-3,000 जोड़ता है। मानक पैकेज में शामिल: सर्जरी, इम्प्लांट, 3-5 दिन का प्रवास, बेसिक PT, फॉलो-अप। बाहर लेकिन आमतौर पर आवश्यक: विस्तारित PT (अक्सर रिकवरी होटल में 2-4 सप्ताह), घर के देश की PT योजना, डिस्चार्ज के बाद की दवाएँ। विस्तारित प्रवास, ट्रांज़िट, और आवास शामिल करने पर कुल संख्या हेडलाइन पैकेज मूल्य से 15-25% अधिक होने पर आश्चर्यचकित न हों। कुल यात्रा लागत: एकपक्षीय के लिए $7,000-10,000, द्विपक्षीय के लिए $10,500-14,000।",
      pt: "A prótese total de joelho custa $4.500-7.000 nos melhores centros indianos (Apollo, Fortis, Max). Bilateral simultânea custa $7.500-10.500. Assistida por robô (MAKO) adiciona $1.500-3.000 à base. Incluído em pacotes padrão: cirurgia, implante, 3-5 dias de internação, fisioterapia básica, seguimento. Excluído mas tipicamente necessário: fisioterapia estendida (frequentemente 2-4 semanas em hotel de recuperação), plano de fisioterapia no país de origem, medicações pós-alta. Não se surpreenda que o número total seja 15-25% maior que o preço de pacote de manchete depois de incluir estadia estendida, trânsito e hospedagem. Custo total da viagem: $7.000-10.000 para unilateral, $10.500-14.000 para bilateral.",
      ru: "Тотальное эндопротезирование колена стоит 4 500-7 000 $ в ведущих индийских центрах (Apollo, Fortis, Max). Билатеральное одновременное — 7 500-10 500 $. Роботическая ассистенция (MAKO) добавляет 1 500-3 000 $ к базовой стоимости. Включено в стандартные пакеты: операция, имплант, пребывание 3-5 дней, базовая физиотерапия, наблюдение. Исключено, но обычно необходимо: расширенная физиотерапия (часто 2-4 недели в отеле восстановления), план физиотерапии в родной стране, лекарства после выписки. Не удивляйтесь, что итоговая сумма на 15-25% выше заголовочной цены пакета после включения расширенного пребывания, транзита и проживания. Общая стоимость поездки: 7 000-10 000 $ за одну сторону, 10 500-14 000 $ за двустороннее.",
      tr: "En iyi Hint merkezlerinde (Apollo, Fortis, Max) tam diz protezi $4.500-7.000 arasındadır. Eş zamanlı bilateral $7.500-10.500. Robot destekli (MAKO) tabana $1.500-3.000 ekler. Standart paketlere dahil: ameliyat, implant, 3-5 gün yatış, temel fizyoterapi, takip. Hariç ama tipik olarak gerekli: uzatılmış fizyoterapi (sıklıkla iyileşme otelinde 2-4 hafta), ülke fizyoterapi planı, taburculuk sonrası ilaçlar. Uzatılmış konaklama, transit ve barınma dahil edildiğinde toplam rakamın manşet paket fiyatından %15-25 daha yüksek olmasına şaşırmayın. Toplam seyahat maliyeti: tek taraflı için $7.000-10.000, bilateral için $10.500-14.000." }
  },
  { id: 87,
    q: { ar: "ما تكلفة أطفال الأنابيب في الهند؟", bn: "ভারতে IVF এর খরচ কত?", fr: "Quel est le coût d’une FIV en Inde ?", hi: "भारत में IVF की लागत क्या है?", pt: "Qual é o custo da FIV na Índia?", ru: "Сколько стоит ЭКО в Индии?", tr: "Hindistan'da tüp bebek maliyeti nedir?" },
    a: { ar: "دورة أطفال الأنابيب القياسية في الهند: 2,500$-4,500$ لكل دورة في البرامج الراسخة (Apollo، Fortis، Manipal، Nova). الإضافات: • ICSI (الحقن المجهري للحيوانات المنوية): +300-600$. • PGT-A (الفحص الوراثي للأجنة): +1,500-2,500$. • PGT-M (مرض وراثي محدد): +2,000-3,500$. • دورة بويضات متبرعة: +2,000-4,000$ (تعويض المتبرعة يختلف). • تجميد البويضات: 2,500-4,000$. مقارنة بالولايات المتحدة: أطفال الأنابيب القياسية عادةً 15,000-25,000$ لكل دورة؛ بويضات متبرعة 30,000-45,000$. معظم المرضى يحتاجون 1.5-2.5 دورة لتحقيق ولادة حية. باقة متعددة الدورات أو برنامج 'مخاطر مشتركة' قد يكون ذكيًا للمرضى في فئات عمرية متوسطة النجاح.",
      bn: "ভারতে স্ট্যান্ডার্ড IVF সাইকেল: প্রতিষ্ঠিত প্রোগ্রামে (Apollo, Fortis, Manipal, Nova) প্রতি সাইকেলে $২,৫০০-৪,৫০০। অ্যাড-অন: • ICSI (ইন্ট্রাসাইটোপ্লাজমিক স্পার্ম ইনজেকশন): +$৩০০-৬০০। • PGT-A (এমব্রায়োর জেনেটিক স্ক্রিনিং): +$১,৫০০-২,৫০০। • PGT-M (নির্দিষ্ট জেনেটিক রোগ): +$২,০০০-৩,৫০০। • ডোনার ডিম্বাণু সাইকেল: +$২,০০০-৪,০০০ (ডিম্বাণু দাতা ক্ষতিপূরণ পরিবর্তিত হয়)। • ডিম্বাণু ফ্রিজিং: $২,৫০০-৪,০০০। US-এর সাথে তুলনা: স্ট্যান্ডার্ড IVF সাধারণত প্রতি সাইকেলে $১৫,০০০-২৫,০০০; ডোনার ডিম্বাণু $৩০,০০০-৪৫,০০০। বেশিরভাগ রোগীর একটি জীবিত শিশুর জন্য ১.৫-২.৫ সাইকেল প্রয়োজন। মাল্টি-সাইকেল প্যাকেজ বা 'শেয়ার্ড-রিস্ক' প্রোগ্রাম মধ্যম-সাফল্যের হার বয়সের রোগীদের জন্য স্মার্ট হতে পারে।",
      fr: "Cycle FIV standard en Inde : 2 500–4 500 $ par cycle dans les programmes établis (Apollo, Fortis, Manipal, Nova). Options supplémentaires : • ICSI (injection intracytoplasmique de spermatozoïde) : +300–600 $. • PGT-A (dépistage génétique des embryons) : +1 500–2 500 $. • PGT-M (maladie génétique spécifique) : +2 000–3 500 $. • Cycle avec don d’ovocyte : +2 000–4 000 $ (compensation donneuse variable). • Congélation d’ovocytes : 2 500–4 000 $. Comparaison aux États-Unis : FIV standard typiquement 15 000–25 000 $ par cycle ; don d’ovocyte 30 000–45 000 $. La plupart des patientes nécessitent 1,5–2,5 cycles pour obtenir une naissance vivante. Un forfait multi-cycles ou un programme « risque partagé » peut être judicieux pour les patientes dans des tranches d’âge à succès intermédiaire.",
      hi: "भारत में मानक IVF चक्र: स्थापित कार्यक्रमों (Apollo, Fortis, Manipal, Nova) में प्रति चक्र $2,500-4,500। ऐड-ऑन: • ICSI (इंट्रासाइटोप्लाज़्मिक स्पर्म इंजेक्शन): +$300-600। • PGT-A (एम्ब्रियो की आनुवंशिक स्क्रीनिंग): +$1,500-2,500। • PGT-M (विशिष्ट आनुवंशिक रोग): +$2,000-3,500। • दाता अंडाणु चक्र: +$2,000-4,000 (अंडाणु दाता मुआवज़ा भिन्न होता है)। • अंडाणु फ्रीज़िंग: $2,500-4,000। US से तुलना: मानक IVF आमतौर पर प्रति चक्र $15,000-25,000; दाता अंडाणु $30,000-45,000। अधिकांश मरीज़ों को एक जीवित जन्म प्राप्त करने के लिए 1.5-2.5 चक्र की आवश्यकता होती है। मध्य-सफलता-दर आयु बैंड में मरीज़ों के लिए मल्टी-साइकल पैकेज या 'साझा-जोखिम' कार्यक्रम स्मार्ट हो सकता है।",
      pt: "Ciclo padrão de FIV na Índia: $2.500-4.500 por ciclo em programas estabelecidos (Apollo, Fortis, Manipal, Nova). Complementos: • ICSI (injeção intracitoplasmática de espermatozoide): +$300-600. • PGT-A (rastreamento genético de embriões): +$1.500-2.500. • PGT-M (doença genética específica): +$2.000-3.500. • Ciclo com óvulo doado: +$2.000-4.000 (compensação da doadora varia). • Congelamento de óvulos: $2.500-4.000. Comparação com EUA: FIV padrão tipicamente $15.000-25.000 por ciclo; óvulo doado $30.000-45.000. A maioria das pacientes precisa de 1,5-2,5 ciclos para conseguir um nascido vivo. Pacote multi-ciclo ou programa de 'risco compartilhado' pode ser inteligente para pacientes em faixas etárias de sucesso médio.",
      ru: "Стандартный цикл ЭКО в Индии: 2 500-4 500 $ за цикл в зарекомендованных программах (Apollo, Fortis, Manipal, Nova). Дополнения: • ИКСИ (интрацитоплазматическая инъекция сперматозоида): +300-600 $. • PGT-A (генетический скрининг эмбрионов): +1 500-2 500 $. • PGT-M (специфическое генетическое заболевание): +2 000-3 500 $. • Цикл с донорской яйцеклеткой: +2 000-4 000 $ (компенсация донора варьируется). • Заморозка яйцеклеток: 2 500-4 000 $. Сравнение с США: стандартное ЭКО обычно 15 000-25 000 $ за цикл; донорская яйцеклетка 30 000-45 000 $. Большинству пациенток требуется 1,5-2,5 цикла для живорождения. Мульти-цикловый пакет или программа «разделённого риска» могут быть разумны для пациенток в возрастных группах со средним показателем успеха.",
      tr: "Hindistan'da standart tüp bebek siklusu: yerleşmiş programlarda (Apollo, Fortis, Manipal, Nova) siklus başına $2.500-4.500. Eklentiler: • ICSI (intrasitoplazmik sperm enjeksiyonu): +$300-600. • PGT-A (embriyoların genetik taraması): +$1.500-2.500. • PGT-M (spesifik genetik hastalık): +$2.000-3.500. • Donör yumurta siklusu: +$2.000-4.000 (yumurta donörü tazminatı değişir). • Yumurta dondurma: $2.500-4.000. ABD ile karşılaştırma: standart tüp bebek tipik olarak siklus başına $15.000-25.000; donör yumurta $30.000-45.000. Çoğu hasta canlı doğum için 1,5-2,5 siklusa ihtiyaç duyar. Çoklu siklus paketi veya 'paylaşılan risk' programı orta başarı oranı yaş bantlarındaki hastalar için akıllıca olabilir." }
  },
  { id: 116,
    q: { ar: "هل هناك رسوم خفية في السفر الطبي؟", bn: "মেডিকেল ভ্রমণে কি গোপন ফি আছে?", fr: "Y a-t-il des frais cachés dans le voyage médical ?", hi: "क्या चिकित्सा यात्रा में छिपे शुल्क हैं?", pt: "Há taxas ocultas em viagem médica?", ru: "Есть ли скрытые платежи в медицинской поездке?", tr: "Tıbbi seyahatte gizli ücretler var mı?" },
    a: { ar: "رسوم 'مخفية' شائعة تفاجئ المرضى: • رسوم تحويل العملة (1-4%). • رسوم التحويل البنكي (30-80$ لكل تحويل). • رسوم معاملات بطاقات الائتمان الأجنبية (1-3%). • رسوم القبول في المستشفى ليست في الباقة. • رسوم تخدير إضافية ليست في الباقة. • ترقيات حجم أو ماركة الزرعة. • رسوم ICU إذا لزم الأمر بعد الباقة القياسية. • معدلات غرفة يومية إذا امتدت الإقامة. • رسوم صيدلية بعد الأدوية القياسية. • رسوم التصوير أو المختبر المتكررة. • خدمات الترجمة. • رسوم توثيق المستندات للتأمين. مجموع الرسوم الخفية يمكن أن يصل إلى 5-15% فوق سعر الباقة الرئيسي. الطريقة الصحيحة للتجنب: احصل على عرض مفصّل بنودًا مع الاستثناءات المدرجة بوضوح، وضع 10% احتياطًا.",
      bn: "সাধারণ 'গোপন' ফি যা রোগীদের অবাক করে: • মুদ্রা রূপান্তর ফি (১-৪%)। • ওয়্যার ট্রান্সফার ফি (প্রতি ট্রান্সফারে $৩০-৮০)। • ক্রেডিট কার্ড বিদেশী লেনদেন সারচার্জ (১-৩%)। • হাসপাতাল ভর্তি ফি প্যাকেজে নেই। • অ্যানেস্থেসিয়া টপ-আপ প্যাকেজে নেই। • ইমপ্লান্ট আকার বা ব্র্যান্ড আপগ্রেড। • স্ট্যান্ডার্ড প্যাকেজের বাইরে প্রয়োজন হলে ICU ফি। • অবস্থান বাড়লে প্রতি-দিন রুম রেট। • স্ট্যান্ডার্ড ওষুধের বাইরে ফার্মেসি ফি। • ইমেজিং বা ল্যাব পুনরাবৃত্তি ফি। • অনুবাদ পরিষেবা। • বীমার জন্য নথি প্রত্যয়ন ফি। মোট গোপন ফি হেডলাইন প্যাকেজ মূল্যের চেয়ে ৫-১৫% উপরে চলতে পারে। এড়ানোর সঠিক উপায়: পরিষ্কারভাবে তালিকাভুক্ত বর্জনের সাথে আইটেমাইজড কোট পান, এবং ১০% কন্টিনজেন্সি বাজেট করুন।",
      fr: "Frais « cachés » courants qui surprennent les patients : • Frais de conversion de devise (1–4 %). • Frais de virement bancaire (30–80 $ par virement). • Surcharge de transaction étrangère sur carte de crédit (1–3 %). • Frais d’admission à l’hôpital hors forfait. • Compléments d’anesthésie hors forfait. • Mises à niveau de taille ou de marque d’implant. • Frais de réa au-delà du forfait standard. • Tarifs de chambre journaliers si le séjour s’étend. • Frais de pharmacie au-delà des médicaments standards. • Frais de répétition d’imagerie ou laboratoire. • Services de traduction. • Frais de certification de documents pour l’assurance. Le total des frais cachés peut atteindre 5–15 % au-dessus du prix forfait affiché. La bonne façon d’éviter : obtenez un devis détaillé avec exclusions clairement listées, et budgétez 10 % de contingence.",
      hi: "सामान्य 'छिपे' शुल्क जो मरीज़ों को आश्चर्यचकित करते हैं: • मुद्रा रूपांतरण शुल्क (1-4%)। • वायर ट्रांसफर शुल्क (प्रति ट्रांसफर $30-80)। • क्रेडिट कार्ड विदेशी लेनदेन सरचार्ज (1-3%)। • अस्पताल भर्ती शुल्क पैकेज में नहीं। • एनेस्थीसिया टॉप-अप पैकेज में नहीं। • इम्प्लांट आकार या ब्रांड अपग्रेड। • मानक पैकेज से परे आवश्यक होने पर ICU शुल्क। • प्रवास बढ़ने पर प्रति-दिन कमरे की दर। • मानक दवाओं से परे फार्मेसी शुल्क। • इमेजिंग या लैब दोहराव शुल्क। • अनुवाद सेवाएँ। • बीमा के लिए दस्तावेज़ प्रमाणन शुल्क। कुल छिपे शुल्क हेडलाइन पैकेज मूल्य से 5-15% ऊपर चल सकते हैं। बचने का सही तरीका: स्पष्ट रूप से सूचीबद्ध बहिष्करणों के साथ आइटमाइज़्ड कोट प्राप्त करें, और 10% आकस्मिकता बजट करें।",
      pt: "Taxas 'ocultas' comuns que surpreendem pacientes: • Taxas de conversão de moeda (1-4%). • Taxas de transferência bancária ($30-80 por transferência). • Sobretaxa de transação estrangeira em cartão de crédito (1-3%). • Taxas de admissão hospitalar não no pacote. • Complementos de anestesia não no pacote. • Upgrades de tamanho ou marca de implante. • Taxas de UTI se necessário além do pacote padrão. • Tarifas diárias de quarto se a internação se estender. • Taxas de farmácia além de medicamentos padrão. • Taxas de repetição de imagem ou laboratório. • Serviços de tradução. • Taxas de certificação de documentos para seguro. Total de taxas ocultas pode chegar a 5-15% acima do preço de pacote de manchete. A maneira certa de evitar: obtenha orçamento detalhado com exclusões claramente listadas, e reserve 10% de contingência.",
      ru: "Распространённые «скрытые» платежи, которые удивляют пациентов: • Комиссии за конвертацию валют (1-4%). • Комиссии за банковский перевод (30-80 $ за перевод). • Надбавка за иностранную транзакцию по кредитной карте (1-3%). • Плата за госпитализацию не в пакете. • Дополнительная анестезия не в пакете. • Повышение размера или марки импланта. • Плата за ОРИТ при необходимости сверх стандартного пакета. • Суточные тарифы за палату при продлении пребывания. • Аптечные сборы сверх стандартных лекарств. • Сборы за повторные снимки или анализы. • Услуги перевода. • Сборы за заверение документов для страховки. Сумма скрытых платежей может достигать 5-15% сверх заголовочной цены пакета. Правильный способ избежать: получите детализированную смету с чётко указанными исключениями и заложите 10% резерв.",
      tr: "Hastaları şaşırtan yaygın 'gizli' ücretler: • Döviz dönüştürme ücretleri (%1-4). • Banka havale ücretleri (havale başına $30-80). • Kredi kartı yabancı işlem ek ücreti (%1-3). • Pakette olmayan hastane kabul ücretleri. • Pakette olmayan anestezi ek ücretleri. • İmplant boyut veya marka yükseltmeleri. • Standart paket dışında gerekirse yoğun bakım ücretleri. • Yatış uzarsa günlük oda ücretleri. • Standart ilaçların ötesinde eczane ücretleri. • Görüntüleme veya laboratuvar tekrar ücretleri. • Çeviri hizmetleri. • Sigorta için belge onay ücretleri. Toplam gizli ücretler manşet paket fiyatının %5-15 üzerine çıkabilir. Önlemenin doğru yolu: hariç tutmaları açıkça listelenen kalem kalem teklif alın ve %10 olasılık bütçesi ayırın." }
  },
];

async function main() {
  let inserted = 0, updated = 0;
  for (const qa of QAS) {
    for (const locale of LOCALES) {
      for (const [field, value] of [["question", qa.q[locale]], ["answer", qa.a[locale]]] as const) {
        const result = await db.execute(sql`
          INSERT INTO translations (translatable_type, translatable_id, locale, field_name, value,
                                    is_machine_translated, is_reviewed, reviewed_by, reviewed_at)
          VALUES ('qa_post', ${qa.id}, ${locale}, ${field}, ${value}, false, true, 'manual-wave2.15a', NOW())
          ON CONFLICT (translatable_type, translatable_id, locale, field_name)
          DO UPDATE SET value = EXCLUDED.value, is_machine_translated = false, is_reviewed = true,
                        reviewed_by = 'manual-wave2.15a', reviewed_at = NOW(), updated_at = NOW()
          RETURNING (xmax = 0) AS inserted
        `);
        const row = Array.from(result as any)[0] as any;
        if (row?.inserted) inserted++; else updated++;
      }
    }
  }
  console.log(`Wave 2.15a complete: inserted=${inserted} updated=${updated}`);
  console.log(`Total: ${inserted + updated} (${QAS.length} Q&A × ${LOCALES.length} locales × 2 fields)`);
  process.exit(0);
}
main().catch((e) => { console.error(e); process.exit(1); });
