/**
 * Wave 2.20a — first 30 blog posts × 7 locales × 2 fields (title + excerpt) = 420 strings.
 * Lights up blog listing card titles + previews in all 7 non-EN locales.
 * Body content stays EN (translating 1,200-word bodies × 7 locales infeasible by hand).
 */
import { db } from "../src/lib/db";
import { sql } from "drizzle-orm";

type Locale = "ar" | "bn" | "fr" | "hi" | "pt" | "ru" | "tr";
const LOCALES: Locale[] = ["ar", "bn", "fr", "hi", "pt", "ru", "tr"];

interface B { id: number; t: Record<Locale, string>; e: Record<Locale, string>; }

const POSTS: B[] = [
  { id: 1,
    t: { ar: "كيف تختار مستشفى لجراحة CABG في الخارج", bn: "বিদেশে CABG-এর জন্য হাসপাতাল কীভাবে নির্বাচন করবেন", fr: "Comment choisir un hôpital à l’étranger pour un CABG", hi: "विदेश में CABG के लिए अस्पताल कैसे चुनें", pt: "Como escolher um hospital no exterior para CABG", ru: "Как выбрать больницу за рубежом для АКШ", tr: "Yurt dışında CABG için hastane nasıl seçilir" },
    e: { ar: "معظم مرضى CABG الدوليين يختارون بناءً على السعر — والجراحون يقولون إنه فلتر خاطئ. ما الذي يتنبأ فعلًا بالنتائج؟", bn: "বেশিরভাগ আন্তর্জাতিক CABG রোগী দাম দেখে নির্বাচন করেন — সার্জনরা বলেন এটি ভুল ফিল্টার। প্রকৃত ফলাফলের সূচক কী?", fr: "La plupart des patients internationaux choisissent au prix — c’est le mauvais filtre selon les chirurgiens. Voici les vrais prédicteurs.", hi: "अधिकांश अंतरराष्ट्रीय CABG मरीज़ मूल्य देखकर चुनते हैं — सर्जनों के अनुसार यह गलत फिल्टर है। असली परिणाम संकेतक क्या हैं?", pt: "A maioria dos pacientes internacionais de CABG escolhe pelo preço — os cirurgiões dizem que é o filtro errado. O que realmente prevê os resultados?", ru: "Большинство иностранных пациентов выбирают по цене — хирурги говорят, это неправильный фильтр. Что действительно предсказывает исход?", tr: "Çoğu uluslararası CABG hastası fiyata bakar — cerrahlar bunun yanlış filtre olduğunu söylüyor. Sonuçları gerçekten ne tahmin eder?" }
  },
  { id: 2,
    t: { ar: "تأشيرة طبية أم سياحية: أيهما تحتاج فعلًا؟", bn: "মেডিকেল ভিসা বনাম ট্যুরিস্ট ভিসা: কোনটি আসলে দরকার?", fr: "Visa médical ou visa touristique : lequel vous faut-il vraiment ?", hi: "मेडिकल वीज़ा बनाम पर्यटक वीज़ा: वास्तव में किसकी ज़रूरत है?", pt: "Visto médico ou visto turístico: qual você realmente precisa?", ru: "Медицинская или туристическая виза: что вам действительно нужно?", tr: "Tıbbi vize mi turist vizesi mi: gerçekten hangisi gerekli?" },
    e: { ar: "إذا كان الإجراء أقل من 30 يومًا وجنسيتك تحصل على تأشيرة عند الوصول، فلن تحتاج تأشيرة طبية. للزراعة وحالات الأورام متعددة المراحل، تحتاجها — هذه مصفوفة القرار.", bn: "যদি প্রক্রিয়া ৩০ দিনের কম হয় এবং আপনার জাতীয়তা অন-অ্যারাইভাল ভিসা পায়, মেডিকেল ভিসার দরকার নেই। ট্রান্সপ্ল্যান্ট, বহু-পর্যায়ের অনকোলজিতে দরকার — সিদ্ধান্তের ম্যাট্রিক্স এখানে।", fr: "Pour un acte de moins de 30 jours et avec visa à l’arrivée, le visa médical n’est pas nécessaire. Pour une greffe ou un cas oncologique multi-étapes, il l’est. Voici la matrice.", hi: "यदि प्रक्रिया 30 दिन से कम है और आपको ऑन-अराइवल वीज़ा मिलता है, तो मेडिकल वीज़ा की ज़रूरत नहीं। प्रत्यारोपण और बहु-चरण ऑन्कोलॉजी मामलों में चाहिए — निर्णय मैट्रिक्स यहाँ।", pt: "Se o procedimento dura menos de 30 dias e sua nacionalidade tem visto na chegada, você provavelmente não precisa do visto médico. Para transplantes e oncologia multi-etapa, sim. Aqui está a matriz.", ru: "Если процедура менее 30 дней и у вас виза по прибытии, медицинская виза не нужна. Для трансплантаций и многоэтапной онкологии — нужна. Вот матрица решений.", tr: "30 günden kısa prosedür ve kapıda vize alıyorsanız tıbbi vizeye gerek yok. Nakil ve çok aşamalı onkoloji vakalarında gerekli — karar matrisi burada." }
  },
  { id: 3,
    t: { ar: "لماذا نوصي 28% من حالات الرأي الثاني بعدم إجراء العملية", bn: "কেন আমরা ২৮% সেকেন্ড ওপিনিয়নে সার্জারির বিরুদ্ধে পরামর্শ দিই", fr: "Pourquoi 28 % de nos seconds avis déconseillent la chirurgie", hi: "क्यों हमारी 28% दूसरी राय सर्जरी न कराने की सलाह देती है", pt: "Por que 28% das nossas segundas opiniões recomendam não operar", ru: "Почему 28% наших вторых мнений рекомендуют отказаться от операции", tr: "İkinci görüşlerimizin %28'i neden ameliyat önermiyor" },
    e: { ar: "من أصل 2,300+ رأي ثانٍ كتبه فريقنا العام الماضي، أوصى 28% بخيار أقل توغّلاً مما اقتُرح أصلًا. ها هو التفصيل وما يعنيه عند اتخاذ قرارك.", bn: "গত বছর আমাদের প্যানেল লিখেছিল ২৩০০+ সেকেন্ড ওপিনিয়ন; ২৮% মূল প্রস্তাবের চেয়ে কম আক্রমণাত্মক বিকল্প পরামর্শ দিয়েছিল। বিভাজন এবং সিদ্ধান্তে এর অর্থ এখানে।", fr: "Sur les 2 300+ seconds avis rédigés l’an dernier par notre panel, 28 % ont recommandé une option moins invasive que celle proposée. Voici la répartition et ce que ça signifie.", hi: "पिछले साल हमारे पैनल ने 2,300+ दूसरी राय लिखीं; 28% ने मूल प्रस्ताव से कम आक्रामक विकल्प की सिफारिश की। विवरण और निर्णय के लिए इसका अर्थ यहाँ।", pt: "Das mais de 2.300 segundas opiniões que nosso painel escreveu no último ano, 28% recomendaram opção menos invasiva que a proposta original. Aqui está a divisão e o que isso significa.", ru: "Из более чем 2 300 вторых мнений, написанных нашей панелью в прошлом году, 28% рекомендовали менее инвазивный вариант. Вот разбивка и что это значит для вашего решения.", tr: "Geçen yıl panelimizin yazdığı 2.300+ ikinci görüşten %28'i orijinal öneriden daha az invaziv bir seçenek önerdi. İşte dağılım ve karar için ne anlama geliyor." }
  },
  { id: 4,
    t: { ar: "العملة، التأمين، والدفع المسبق: كيف تتلقى المستشفيات في الخارج المدفوعات", bn: "মুদ্রা, বীমা ও অগ্রিম পেমেন্ট: বিদেশে হাসপাতাল কীভাবে পেমেন্ট নেয়", fr: "Devise, assurance et acompte : comment les hôpitaux à l’étranger se font payer", hi: "मुद्रा, बीमा, और अग्रिम भुगतान: विदेश में अस्पताल कैसे भुगतान लेते हैं", pt: "Moeda, seguro e pagamento antecipado: como hospitais no exterior recebem", ru: "Валюта, страховка и предоплата: как больницы за рубежом принимают оплату", tr: "Para birimi, sigorta ve ön ödeme: yurt dışı hastaneler ödemeyi nasıl alıyor" },
    e: { ar: "معظم المستشفيات الدولية تطلب 50% على الأقل قبل الإدخال، والباقي عند الخروج. التحويل والتحويلات البنكية والفوترة المباشرة للتأمين — ما تتوقعه حسب الوجهة.", bn: "বেশিরভাগ আন্তর্জাতিক হাসপাতাল ভর্তির আগে অন্তত ৫০% চায়, বাকি ৫০% ছাড়ার সময়। মুদ্রা রূপান্তর, ওয়্যার ট্রান্সফার, বীমা সরাসরি বিলিং — গন্তব্যভেদে কী আশা করবেন।", fr: "La plupart des hôpitaux internationaux exigent au moins 50 % avant l’admission, le solde à la sortie. Conversion de devises, virements, tiers payant — voici ce qui vous attend par destination.", hi: "अधिकांश अंतरराष्ट्रीय अस्पताल भर्ती से पहले कम से कम 50% मांगते हैं, बाकी डिस्चार्ज पर। मुद्रा रूपांतरण, वायर ट्रांसफर, बीमा डायरेक्ट-बिलिंग — गंतव्य-वार क्या अपेक्षा करें।", pt: "A maioria dos hospitais internacionais quer pelo menos 50% antes da internação; o restante na alta. Câmbio, transferências internacionais, faturamento direto de seguro — o que esperar por destino.", ru: "Большинство международных больниц требуют не менее 50% до госпитализации, остальное при выписке. Конвертация валют, переводы, прямое выставление счетов страховщику — что ожидать по странам.", tr: "Çoğu uluslararası hastane yatış öncesi en az %50 ister, kalanı taburculukta. Döviz çevirme, banka havalesi, sigorta doğrudan faturalama — destinasyona göre beklentiler." }
  },
  { id: 5,
    t: { ar: "التكلفة الفعلية لعملية CABG في الهند مقابل تايلاند مقابل تركيا", bn: "ভারত বনাম থাইল্যান্ড বনাম তুরস্কে CABG-এর প্রকৃত খরচ", fr: "Le vrai coût d’un CABG en Inde, Thaïlande et Turquie", hi: "भारत बनाम थाईलैंड बनाम तुर्की में CABG की वास्तविक लागत", pt: "O custo real do CABG na Índia, Tailândia e Turquia", ru: "Реальная стоимость АКШ в Индии, Таиланде и Турции", tr: "Hindistan, Tayland ve Türkiye'de CABG'nin gerçek maliyeti" },
    e: { ar: "مقارنة بنود صريحة لتكاليف جراحة المجازة عبر الوجهات الكبرى الثلاث، بما فيها الرسوم المخفية التي يفوّتها معظم المرضى.", bn: "তিনটি প্রধান গন্তব্যে বাইপাস সার্জারির খরচের সৎ লাইন-আইটেম তুলনা, বেশিরভাগ রোগী যে গোপন ফি মিস করেন তা সহ।", fr: "Une comparaison ligne par ligne des coûts du pontage entre les trois grandes destinations, frais cachés inclus.", hi: "तीन प्रमुख गंतव्यों में बायपास सर्जरी की लागत की ईमानदार आइटम-वार तुलना, छिपे शुल्क सहित जो ज़्यादातर मरीज़ चूकते हैं।", pt: "Uma comparação honesta item por item dos custos da ponte entre os três principais destinos, incluindo taxas ocultas que a maioria dos pacientes perde.", ru: "Честное построчное сравнение стоимости шунтирования по трём основным направлениям, включая скрытые платежи, которые упускают пациенты.", tr: "Bypass cerrahisi maliyetlerinin üç büyük destinasyon arasında dürüst kalem kalem karşılaştırması, çoğu hastanın kaçırdığı gizli ücretler dahil." }
  },
  { id: 6,
    t: { ar: "أطفال الأنابيب: تسعير المخاطرة المشتركة مقابل الدورة — أيهما أوفر؟", bn: "আইভিএফ: শেয়ার্ড-রিস্ক বনাম প্রতি-সাইকেল মূল্য — কোনটি আর্থিকভাবে অর্থবহ?", fr: "FIV : forfait risque partagé ou par cycle — qu’est-ce qui est rentable ?", hi: "आईवीएफ: साझा-जोखिम बनाम प्रति-चक्र मूल्य निर्धारण — क्या वित्तीय रूप से समझदारी है?", pt: "FIV: risco compartilhado ou pagamento por ciclo — qual faz sentido financeiro?", ru: "ЭКО: пакет с разделённым риском или оплата за цикл — что выгоднее?", tr: "Tüp bebek: paylaşılan risk vs siklus başı fiyat — hangisi finansal olarak mantıklı?" },
    e: { ar: "حسابات باقات أطفال الأنابيب متعددة الدورات ومتى توفر فعلًا. وأي فئة عمرية تفقد فيها المخاطرة المشتركة قيمتها.", bn: "মাল্টি-সাইকেল আইভিএফ প্যাকেজের পেছনের গণিত এবং কখন তারা প্রকৃতপক্ষে অর্থ সাশ্রয় করে। প্লাস বয়স ব্যান্ড যেখানে শেয়ার্ড-রিস্ক তার মূল্য হারায়।", fr: "Les calculs derrière les forfaits FIV multi-cycles et quand ils font économiser. Plus la tranche d’âge où le risque partagé perd son intérêt.", hi: "मल्टी-साइकिल आईवीएफ पैकेजों के पीछे की गणित और कब वे वास्तव में पैसा बचाते हैं। साथ ही वह आयु वर्ग जहाँ साझा-जोखिम अपना मूल्य खो देता है।", pt: "A matemática por trás dos pacotes de FIV multi-ciclo e quando realmente economizam. Plus a faixa etária em que o risco compartilhado perde valor.", ru: "Математика мульти-цикловых пакетов ЭКО и когда они действительно экономят. Плюс возрастная группа, в которой разделённый риск теряет смысл.", tr: "Çoklu siklus tüp bebek paketlerinin matematiği ve gerçekten ne zaman tasarruf sağladıkları. Ayrıca paylaşılan riskin değer kaybettiği yaş bandı." }
  },
  { id: 7,
    t: { ar: "تكلفة زراعة الكبد والكلى: الهند مقابل تركيا مقابل ألمانيا", bn: "লিভার ও কিডনি ট্রান্সপ্ল্যান্ট খরচ: ভারত বনাম তুরস্ক বনাম জার্মানি", fr: "Coût des greffes hépatique et rénale : Inde, Turquie, Allemagne", hi: "लीवर और गुर्दा प्रत्यारोपण लागत: भारत बनाम तुर्की बनाम जर्मनी", pt: "Custo do transplante de fígado e rim: Índia, Turquia, Alemanha", ru: "Стоимость трансплантации печени и почки: Индия, Турция, Германия", tr: "Karaciğer ve böbrek nakli maliyeti: Hindistan, Türkiye, Almanya" },
    e: { ar: "لماذا تتفاوت تكلفة الزراعة 3-5 أضعاف عبر الوجهات، وأي العوامل تهم فعلًا للنتائج.", bn: "কেন ট্রান্সপ্ল্যান্ট খরচ গন্তব্যভেদে ৩-৫× পরিবর্তিত হয়, এবং কোন উপাদান সত্যিই ফলাফলের জন্য গুরুত্বপূর্ণ।", fr: "Pourquoi le coût d’une greffe varie de 3 à 5× selon la destination, et quels facteurs comptent vraiment pour le résultat.", hi: "क्यों प्रत्यारोपण लागत गंतव्यों में 3-5× भिन्न होती है, और परिणाम के लिए कौन से कारक वास्तव में मायने रखते हैं।", pt: "Por que o custo do transplante varia 3-5× entre destinos, e quais fatores realmente importam para o resultado.", ru: "Почему стоимость трансплантации различается в 3-5 раз по странам, и какие факторы действительно важны для исхода.", tr: "Nakil maliyetinin destinasyonlar arasında neden 3-5× değiştiği ve sonuç için gerçekten hangi faktörlerin önemli olduğu." }
  },
  { id: 8,
    t: { ar: "ما الذي يكلّفه السياحة الطبية فعلًا بعد إضافة كل شيء", bn: "সবকিছু যোগ করার পর মেডিকেল ট্যুরিজম আসলে কত খরচ হয়", fr: "Ce que coûte vraiment le tourisme médical, tout compris", hi: "सब कुछ जोड़ने के बाद मेडिकल टूरिज़्म वास्तव में कितना खर्च होता है", pt: "O que o turismo médico realmente custa quando tudo é somado", ru: "Сколько на самом деле стоит медицинский туризм со всеми расходами", tr: "Her şey eklendiğinde tıbbi turizm gerçekten ne kadara mal olur" },
    e: { ar: "السعر الرئيسي للإجراء نادرًا ما يكون الصورة الكاملة. هذه هي الحسابات التي نجريها لكل مريض — بما فيها البنود التي لا يعرضها معظم المنسقين.", bn: "শিরোনাম পদ্ধতি মূল্য খুব কমই পূর্ণ চিত্র। আমরা প্রতিটি রোগীর জন্য যে গণিত চালাই — বেশিরভাগ সমন্বয়কারীরা যে আইটেমগুলি দেখান না সেগুলো সহ।", fr: "Le prix annoncé de l’intervention n’est rarement le tableau complet. Voici les calculs que nous faisons pour chaque patient — y compris les postes que la plupart des coordinateurs n’affichent pas.", hi: "हेडलाइन प्रक्रिया मूल्य शायद ही पूरी तस्वीर है। हम हर मरीज़ के लिए जो गणित करते हैं — उन वस्तुओं सहित जो ज़्यादातर समन्वयक नहीं दिखाते।", pt: "O preço do procedimento raramente é o retrato completo. Aqui estão as contas que fazemos para cada paciente — incluindo os itens que a maioria dos coordenadores não mostra.", ru: "Заявленная цена процедуры редко даёт полную картину. Вот расчёт, который мы делаем для каждого пациента — включая статьи, которые большинство координаторов не показывают.", tr: "Manşet prosedür fiyatı nadiren tam tablodur. Her hasta için yaptığımız hesap — çoğu koordinatörün göstermediği kalemler dahil." }
  },
  { id: 9,
    t: { ar: "استراتيجيات صرف العملات للسفر الطبي", bn: "মেডিকেল ভ্রমণের জন্য মুদ্রা বিনিময় কৌশল", fr: "Stratégies de change pour le voyage médical", hi: "चिकित्सा यात्रा के लिए मुद्रा विनिमय रणनीतियाँ", pt: "Estratégias de câmbio para viagens médicas", ru: "Стратегии обмена валют для медицинского путешествия", tr: "Tıbbi seyahat için döviz değiştirme stratejileri" },
    e: { ar: "تقلبات الصرف بنسبة 5-10% على مدى 60 يومًا شائعة وقد تمحو وفوراتك. هكذا تثبّت الأسعار وتقلّل الرسوم.", bn: "৬০ দিনে ৫-১০% FX সুইং সাধারণ এবং আপনার সঞ্চয় মুছে দিতে পারে। কীভাবে রেট লক করবেন এবং ফি কমাবেন।", fr: "Des variations de change de 5 à 10 % sur 60 jours sont courantes et peuvent annuler vos économies. Voici comment verrouiller les taux et réduire les frais.", hi: "60 दिनों में 5-10% की FX उतार-चढ़ाव आम है और आपकी बचत मिटा सकती है। दरों को लॉक करने और फीस कम करने का तरीका।", pt: "Oscilações cambiais de 5-10% em 60 dias são comuns e podem anular sua economia. Como travar taxas e minimizar tarifas.", ru: "Колебания курса 5-10% за 60 дней — обычное дело и могут уничтожить вашу экономию. Как зафиксировать курсы и минимизировать комиссии.", tr: "60 günde %5-10 döviz dalgalanması yaygın ve tasarruflarınızı silebilir. Kurları nasıl sabitleyeceğiniz ve ücretleri en aza indireceğiniz." }
  },
  { id: 10,
    t: { ar: "تعويض التأمين للرعاية الطبية الدولية: نتائج واقعية", bn: "আন্তর্জাতিক চিকিৎসার জন্য বীমা প্রতিদান: বাস্তব ফলাফল", fr: "Remboursement par l’assurance pour soins internationaux : la réalité", hi: "अंतरराष्ट्रीय चिकित्सा देखभाल के लिए बीमा प्रतिपूर्ति: यथार्थवादी परिणाम", pt: "Reembolso de seguro para cuidados médicos internacionais: o realista", ru: "Возмещение от страховой за международное лечение: реальные исходы", tr: "Uluslararası tıbbi bakım için sigorta geri ödemesi: gerçekçi sonuçlar" },
    e: { ar: "هل سيدفع تأمينك مقابل العلاج في الخارج؟ الجواب الصادق لمرضى الولايات المتحدة وبريطانيا والاتحاد الأوروبي وكندا.", bn: "আপনার বীমা কি বিদেশে চিকিৎসার জন্য আপনাকে ফেরত দেবে? US, UK, EU, এবং কানাডিয়ান রোগীদের জন্য সৎ উত্তর।", fr: "Votre assurance vous remboursera-t-elle un traitement à l’étranger ? La réponse honnête pour les patients US, UK, UE et canadiens.", hi: "क्या आपका बीमा आपको विदेश में इलाज के लिए वापस भुगतान करेगा? US, UK, EU और कनाडाई मरीज़ों के लिए ईमानदार उत्तर।", pt: "Seu seguro vai reembolsar tratamento no exterior? A resposta honesta para pacientes dos EUA, UK, UE e Canadá.", ru: "Возместит ли ваша страховка лечение за рубежом? Честный ответ для пациентов США, Великобритании, ЕС и Канады.", tr: "Sigortanız yurt dışı tedaviyi geri ödeyecek mi? ABD, Birleşik Krallık, AB ve Kanada hastaları için dürüst cevap." }
  },
  { id: 11,
    t: { ar: "هل أحتاج فعلًا إلى استبدال مفصل الركبة؟", bn: "আমার কি সত্যিই হাঁটু প্রতিস্থাপন দরকার?", fr: "Ai-je vraiment besoin d’une prothèse du genou ?", hi: "क्या मुझे वास्तव में घुटना प्रत्यारोपण की ज़रूरत है?", pt: "Eu realmente preciso de uma prótese de joelho?", ru: "Нужно ли мне на самом деле эндопротезирование колена?", tr: "Gerçekten diz protezine ihtiyacım var mı?" },
    e: { ar: "إطار قرار قبل الالتزام بالجراحة، يشمل 6 أشياء يجب تجربتها أولًا تنجح مع كثير من المرضى.", bn: "সার্জারিতে যাওয়ার আগে একটি সিদ্ধান্ত কাঠামো, ৬টি জিনিস সহ যা প্রথমে চেষ্টা করা যেতে পারে — অনেক রোগীর জন্য কাজ করে।", fr: "Un cadre de décision avant de s’engager dans l’opération, dont 6 choses à essayer d’abord qui marchent pour beaucoup.", hi: "सर्जरी के लिए प्रतिबद्ध होने से पहले एक निर्णय ढांचा, जिसमें 6 चीज़ें शामिल हैं जो पहले आज़मानी चाहिए — बहुत मरीज़ों के लिए कारगर।", pt: "Um framework de decisão antes de se comprometer com a cirurgia, incluindo 6 coisas para tentar primeiro que funcionam para muitos pacientes.", ru: "Алгоритм принятия решения до согласия на операцию, включая 6 вещей для попытки сначала — работают у многих пациентов.", tr: "Cerrahiye karar vermeden önce bir karar çerçevesi, birçok hastada işe yarayan ilk denemeniz gereken 6 şey dahil." }
  },
  { id: 12,
    t: { ar: "متى وكيف تحصل على رأي ثانٍ في السرطان", bn: "ক্যান্সারে কখন এবং কীভাবে দ্বিতীয় মতামত নেবেন", fr: "Quand (et comment) demander un second avis en cancérologie", hi: "कैंसर पर दूसरी राय कब और कैसे लें", pt: "Quando (e como) buscar segunda opinião em câncer", ru: "Когда и как получить второе мнение по онкологии", tr: "Kanserde ne zaman (ve nasıl) ikinci görüş alınır" },
    e: { ar: "خطة الفحوصات والعلاج تستحق نظرة ثانية. متى يهم الأمر أكثر وكيف تحصل على رأي حقيقي.", bn: "একটি স্টেজিং ওয়ার্কআপ ও চিকিৎসা পরিকল্পনা দ্বিতীয়বার দেখার যোগ্য। কখন এটি সবচেয়ে বেশি গুরুত্বপূর্ণ এবং কীভাবে আসলে পান।", fr: "Un bilan d’extension et un plan de traitement méritent un second regard. Quand cela compte le plus et comment l’obtenir vraiment.", hi: "स्टेजिंग वर्कअप और उपचार योजना दूसरी नज़र के योग्य है। यह सबसे ज़्यादा कब मायने रखता है और वास्तव में एक कैसे प्राप्त करें।", pt: "Um estadiamento e plano de tratamento merecem um segundo olhar. Quando importa mais e como obter um de verdade.", ru: "Стадирование и план лечения заслуживают второго взгляда. Когда это важнее всего и как получить второе мнение по-настоящему.", tr: "Bir evreleme ve tedavi planı ikinci bir bakışı hak eder. En önemli ne zaman ve gerçekten nasıl alınır." }
  },
  { id: 13,
    t: { ar: "سرطان البروستاتا: الجراحة، الإشعاع، أم المراقبة النشطة؟", bn: "প্রোস্টেট ক্যান্সার: সার্জারি, রেডিয়েশন, না সক্রিয় পর্যবেক্ষণ?", fr: "Cancer de la prostate : chirurgie, radiothérapie ou surveillance active ?", hi: "प्रोस्टेट कैंसर: सर्जरी, विकिरण, या सक्रिय निगरानी?", pt: "Câncer de próstata: cirurgia, radiação ou vigilância ativa?", ru: "Рак простаты: хирургия, лучевая терапия или активное наблюдение?", tr: "Prostat kanseri: cerrahi, radyasyon veya aktif izleme?" },
    e: { ar: "المسارات الثلاثة الرئيسية لسرطان البروستاتا الموضعي لها نتائج طويلة المدى متشابهة لكن آثار جانبية مختلفة جدًا. كيف تختار.", bn: "স্থানীয় প্রোস্টেট ক্যান্সারের তিনটি মূল পথের দীর্ঘমেয়াদী ফলাফল একই কিন্তু পার্শ্বপ্রতিক্রিয়া প্রোফাইল খুব ভিন্ন। কীভাবে নির্বাচন করবেন।", fr: "Les trois voies principales pour un cancer prostatique localisé ont des résultats à long terme similaires mais des profils d’effets secondaires très différents. Comment choisir.", hi: "स्थानीय प्रोस्टेट कैंसर के तीन मुख्य रास्तों के दीर्घकालिक परिणाम समान हैं लेकिन साइड-इफेक्ट प्रोफ़ाइल बहुत अलग है। कैसे चुनें।", pt: "Os três caminhos principais para câncer de próstata localizado têm resultados de longo prazo semelhantes, mas perfis de efeitos colaterais muito diferentes. Como escolher.", ru: "Три основных пути при локализованном раке простаты дают похожие долгосрочные результаты, но очень разные побочные эффекты. Как выбрать.", tr: "Lokalize prostat kanseri için üç ana yolun uzun vadeli kanser sonuçları benzerdir ancak yan etki profilleri çok farklıdır. Nasıl seçilir." }
  },
  { id: 14,
    t: { ar: "هل جراحة العمود الفقري هي القرار الصحيح؟", bn: "মেরুদণ্ড সার্জারি কি সঠিক সিদ্ধান্ত?", fr: "La chirurgie du rachis est-elle le bon choix ?", hi: "क्या रीढ़ की सर्जरी सही निर्णय है?", pt: "A cirurgia da coluna é a escolha certa?", ru: "Правильное ли решение — хирургия позвоночника?", tr: "Omurga ameliyatı doğru seçim mi?" },
    e: { ar: "نتائج جراحة العمود الفقري متباينة جدًا حسب ما إذا كانت أعراضك جذرية (بالساق) أم محورية (بالظهر). إليك السبب.", bn: "মেরুদণ্ড সার্জারির ফলাফল আপনার লক্ষণগুলি র‍্যাডিকুলার (পা) বা অ্যাক্সিয়াল (পিঠ) কিনা তার উপর নির্ভর করে অত্যন্ত পরিবর্তনশীল। কেন এটি গুরুত্বপূর্ণ।", fr: "Les résultats de la chirurgie rachidienne varient énormément selon que les symptômes sont radiculaires (jambe) ou axiaux (dos). Voici pourquoi c’est important.", hi: "आपके लक्षण रेडिकुलर (पैर) या अक्षीय (पीठ) हैं या नहीं इसके आधार पर रीढ़ की सर्जरी के परिणाम बेहद भिन्न हैं। यह क्यों मायने रखता है।", pt: "Os resultados da cirurgia da coluna variam enormemente conforme os sintomas sejam radiculares (perna) ou axiais (costas). Por que isso importa.", ru: "Исходы операций на позвоночнике сильно различаются в зависимости от того, корешковые ли ваши симптомы (нога) или аксиальные (спина). Почему это важно.", tr: "Omurga cerrahisinin sonuçları belirtilerinizin radiküler (bacak) veya aksiyal (sırt) olmasına göre büyük farklılık gösterir. Neden önemli." }
  },
  { id: 15,
    t: { ar: "إلى أين للجراحة القلبية: إطار قرار", bn: "কার্ডিয়াক সার্জারির জন্য কোথায়: একটি সিদ্ধান্ত কাঠামো", fr: "Où aller pour la chirurgie cardiaque : un cadre de décision", hi: "कार्डियक सर्जरी के लिए कहाँ जाएँ: एक निर्णय फ्रेम", pt: "Para onde ir para cirurgia cardíaca: um framework de decisão", ru: "Куда ехать на кардиохирургию: рамка для принятия решения", tr: "Kalp cerrahisi için nereye: bir karar çerçevesi" },
    e: { ar: "الاختيار بين الهند وتركيا وألمانيا وتايلاند للجراحة القلبية الكبرى — مقارنة منظّمة.", bn: "বড় কার্ডিয়াক সার্জারির জন্য ভারত, তুরস্ক, জার্মানি ও থাইল্যান্ডের মধ্যে নির্বাচন — একটি কাঠামোগত তুলনা।", fr: "Choisir entre Inde, Turquie, Allemagne et Thaïlande pour la chirurgie cardiaque majeure — une comparaison structurée.", hi: "बड़ी कार्डियक सर्जरी के लिए भारत, तुर्की, जर्मनी, और थाईलैंड के बीच चयन — एक संरचित तुलना।", pt: "Escolher entre Índia, Turquia, Alemanha e Tailândia para cirurgia cardíaca de grande porte — uma comparação estruturada.", ru: "Выбор между Индией, Турцией, Германией и Таиландом для крупной кардиохирургии — структурированное сравнение.", tr: "Büyük kalp cerrahisi için Hindistan, Türkiye, Almanya ve Tayland arasında seçim — yapılandırılmış bir karşılaştırma." }
  },
  { id: 16,
    t: { ar: "هل أحتاج إلى أحدث إجراء؟", bn: "আমার কি সবচেয়ে নতুন পদ্ধতি দরকার?", fr: "Faut-il vraiment l’intervention la plus récente ?", hi: "क्या मुझे नवीनतम प्रक्रिया चाहिए?", pt: "Eu preciso do procedimento mais novo?", ru: "Нужна ли мне новейшая процедура?", tr: "En yeni prosedüre ihtiyacım var mı?" },
    e: { ar: "الأحدث ليس دائمًا الأفضل في الجراحة. كيف تقيّم التقنيات المتطورة مقابل الخيارات الراسخة.", bn: "সার্জারিতে নতুন সবসময় ভাল নয়। প্রতিষ্ঠিত বিকল্পগুলির তুলনায় কাটিং-এজ কৌশলগুলি কীভাবে মূল্যায়ন করবেন।", fr: "Plus récent ne veut pas dire meilleur en chirurgie. Comment évaluer les techniques de pointe par rapport aux options établies.", hi: "सर्जरी में नया हमेशा बेहतर नहीं है। स्थापित विकल्पों की तुलना में अत्याधुनिक तकनीकों का मूल्यांकन कैसे करें।", pt: "Mais novo nem sempre é melhor em cirurgia. Como avaliar técnicas de ponta contra opções estabelecidas.", ru: "В хирургии новее не всегда лучше. Как оценивать передовые методы относительно проверенных вариантов.", tr: "Cerrahide yeni her zaman daha iyi değildir. Yerleşik seçeneklere karşı son teknoloji teknikleri nasıl değerlendirilir." }
  },
  { id: 17,
    t: { ar: "كيف تقيّم برنامجًا طبيًا دوليًا من موقعه الإلكتروني", bn: "একটি আন্তর্জাতিক মেডিকেল প্রোগ্রাম তার ওয়েবসাইট দিয়ে কীভাবে মূল্যায়ন করবেন", fr: "Comment évaluer un programme médical international à partir de son site", hi: "वेबसाइट के द्वारा एक अंतरराष्ट्रीय चिकित्सा कार्यक्रम का मूल्यांकन कैसे करें", pt: "Como avaliar um programa médico internacional pelo site", ru: "Как оценить международную медицинскую программу по её сайту", tr: "Bir uluslararası tıbbi programı web sitesinden nasıl değerlendirilir" },
    e: { ar: "ما تقوله مواقع البرامج (وما لا تقوله) عن الجودة. قائمة عملية.", bn: "প্রোগ্রাম ওয়েবসাইট আপনাকে গুণমান সম্পর্কে যা বলে (এবং বলে না)। একটি ব্যবহারিক চেকলিস্ট।", fr: "Ce que les sites des programmes vous disent (et ne vous disent pas) sur la qualité. Une checklist pratique.", hi: "प्रोग्राम वेबसाइट गुणवत्ता के बारे में क्या बताती हैं (और क्या नहीं बताती)। एक व्यावहारिक चेकलिस्ट।", pt: "O que os sites dos programas dizem (e não dizem) sobre qualidade. Um checklist prático.", ru: "Что говорят сайты программ (и о чём умалчивают) о качестве. Практический чек-лист.", tr: "Program web siteleri kalite hakkında size ne anlatır (ve neyi anlatmaz). Pratik bir kontrol listesi." }
  },
  { id: 18,
    t: { ar: "دليل المرافق للسفر الطبي", bn: "মেডিকেল ভ্রমণে সঙ্গীর গাইড", fr: "Le guide de l’accompagnant pour le voyage médical", hi: "चिकित्सा यात्रा के लिए परिचारक मार्गदर्शिका", pt: "Guia do acompanhante para viagem médica", ru: "Руководство для сопровождающего в медицинской поездке", tr: "Tıbbi seyahatte refakatçi rehberi" },
    e: { ar: "ما تتوقعه، ما تأخذه، ودورك الفعلي عند مرافقة شخص للجراحة في الخارج.", bn: "আপনি কাউকে বিদেশে সার্জারির জন্য সঙ্গে নিয়ে গেলে কী আশা করবেন, কী আনবেন, এবং আপনার প্রকৃত ভূমিকা কী।", fr: "Ce qu’il faut attendre, ce qu’il faut emporter, et votre rôle réel quand vous accompagnez quelqu’un à l’étranger pour une opération.", hi: "क्या अपेक्षा करें, क्या लाएँ, और जब आप किसी को सर्जरी के लिए विदेश ले जाते हैं तो आपकी वास्तविक भूमिका क्या है।", pt: "O que esperar, o que levar, e qual é seu papel real ao acompanhar alguém ao exterior para cirurgia.", ru: "Чего ожидать, что взять с собой и какова ваша роль, когда сопровождаете кого-то за границу на операцию.", tr: "Birine ameliyat için yurt dışına eşlik ederken neler bekleneceği, neler getirileceği ve gerçek rolünüzün ne olduğu." }
  },
  { id: 19,
    t: { ar: "ماذا تحزم للسفر الطبي", bn: "মেডিকেল ভ্রমণের জন্য কী প্যাক করবেন", fr: "Que mettre dans sa valise pour un voyage médical", hi: "चिकित्सा यात्रा के लिए क्या पैक करें", pt: "O que levar na mala para viagem médica", ru: "Что взять с собой в медицинскую поездку", tr: "Tıbbi seyahat için ne paketlenir" },
    e: { ar: "قائمة تعبئة عملية للإجراءات الكبرى في الخارج، بناءً على ملاحظات المرضى على مدى 18 شهرًا.", bn: "১৮ মাসের রোগীর প্রতিক্রিয়ার উপর ভিত্তি করে বিদেশে বড় পদ্ধতির জন্য একটি ব্যবহারিক প্যাকিং তালিকা।", fr: "Une liste d’emballage pratique pour les interventions majeures à l’étranger, basée sur les retours patients sur 18 mois.", hi: "18 महीनों में मरीज़ की प्रतिक्रिया के आधार पर विदेश में बड़ी प्रक्रियाओं के लिए एक व्यावहारिक पैकिंग सूची।", pt: "Uma lista de bagagem prática para procedimentos maiores no exterior, com base no feedback de pacientes de 18 meses.", ru: "Практический список вещей для серьёзных процедур за рубежом, основанный на отзывах пациентов за 18 месяцев.", tr: "18 aylık hasta geri bildirimine dayalı, yurt dışında büyük prosedürler için pratik bir paketleme listesi." }
  },
  { id: 20,
    t: { ar: "كيف تنسّق الرعاية المتابعة مع طبيبك المحلي", bn: "আপনার বাড়ির ডাক্তারের সাথে ফলো-আপ যত্ন কীভাবে সমন্বয় করবেন", fr: "Comment coordonner le suivi avec votre médecin traitant", hi: "अपने स्थानीय डॉक्टर के साथ फॉलो-अप देखभाल का समन्वय कैसे करें", pt: "Como coordenar cuidados de seguimento com seu médico em casa", ru: "Как координировать наблюдение с вашим врачом дома", tr: "Ev doktorunuzla takip bakımını nasıl koordine edersiniz" },
    e: { ar: "أكبر خطأ في السفر الطبي هو الرعاية ما بعد العملية المجزأة. هذه هي خطة اللعب.", bn: "মেডিকেল ভ্রমণে সবচেয়ে বড় সমস্যা খণ্ডিত পোস্ট-অপ যত্ন। প্লেবুক এখানে।", fr: "Le plus grand piège du voyage médical est un suivi post-opératoire fragmenté. Voici la marche à suivre.", hi: "मेडिकल ट्रैवल में सबसे बड़ी समस्या खंडित पोस्ट-ऑप देखभाल है। प्लेबुक यहाँ।", pt: "O maior obstáculo na viagem médica é cuidado pós-op fragmentado. Aqui está o playbook.", ru: "Главная проблема медицинских поездок — фрагментированное послеоперационное ведение. Вот план действий.", tr: "Tıbbi seyahatte en büyük tuzak parçalanmış ameliyat sonrası bakımdır. Oyun planı burada." }
  },
  { id: 21,
    t: { ar: "ماذا تفعل إذا حدث شيء خطأ بعد السفر الطبي", bn: "মেডিকেল ভ্রমণের পরে কিছু ভুল হলে কী করবেন", fr: "Que faire si quelque chose tourne mal après un voyage médical", hi: "अगर मेडिकल ट्रैवल के बाद कुछ गलत हो जाए तो क्या करें", pt: "O que fazer se algo der errado após viagem médica", ru: "Что делать, если что-то пошло не так после медицинской поездки", tr: "Tıbbi seyahatten sonra bir şey ters giderse ne yapmalı" },
    e: { ar: "خطة عمل عملية لإدارة المضاعفات بعد العودة — بما في ذلك متى تطير ثانية.", bn: "ফিরে আসার পর জটিলতা পরিচালনার জন্য একটি ব্যবহারিক প্লেবুক — কখন আবার উড়বেন তা সহ।", fr: "Un plan pratique pour gérer les complications après le retour — y compris quand reprendre l’avion.", hi: "लौटने के बाद जटिलताओं को संभालने के लिए एक व्यावहारिक प्लेबुक — कब वापस उड़ें सहित।", pt: "Um playbook prático para lidar com complicações após o retorno — incluindo quando voltar a viajar.", ru: "Практический план действий при осложнениях после возвращения — включая когда стоит лететь обратно.", tr: "Eve döndükten sonra komplikasyonları yönetmek için pratik bir oyun planı — ne zaman geri uçacağınız dahil." }
  },
  { id: 22,
    t: { ar: "كيف توقّت سفرك الطبي للتعافي", bn: "পুনরুদ্ধারের জন্য আপনার মেডিকেল ভ্রমণ কীভাবে সময় নির্ধারণ করবেন", fr: "Comment caler votre voyage médical sur la récupération", hi: "रिकवरी के लिए अपनी चिकित्सा यात्रा का समय कैसे तय करें", pt: "Como cronometrar sua viagem médica para a recuperação", ru: "Как рассчитать время медицинской поездки для восстановления", tr: "Tıbbi seyahatinizi iyileşme için nasıl zamanlayın" },
    e: { ar: "مدة التعافي تختلف بشكل كبير حسب الإجراء. كيف تخطّط لطول الرحلة وغياب العمل وتجهيز المنزل.", bn: "পুনরুদ্ধারের সময়কাল প্রক্রিয়াভেদে ব্যাপকভাবে পরিবর্তিত হয়। ভ্রমণের দৈর্ঘ্য, কাজের অনুপস্থিতি ও বাড়ি প্রস্তুতি কীভাবে পরিকল্পনা করবেন।", fr: "La durée de récupération varie énormément selon l’intervention. Comment planifier la durée du séjour, l’absence professionnelle et la préparation du domicile.", hi: "रिकवरी अवधि प्रक्रिया के अनुसार व्यापक रूप से भिन्न होती है। यात्रा अवधि, काम की अनुपस्थिति, और घर की तैयारी कैसे योजना बनाएँ।", pt: "A duração da recuperação varia muito por procedimento. Como planejar duração da viagem, ausência do trabalho e preparação da casa.", ru: "Длительность восстановления сильно различается по процедурам. Как планировать длину поездки, отсутствие на работе и подготовку дома.", tr: "İyileşme süresi prosedüre göre büyük farklılık gösterir. Seyahat süresi, iş ayrılığı ve ev hazırlığı nasıl planlanır." }
  },
  { id: 23,
    t: { ar: "أرقام حقيقية حول مضاعفات السفر الطبي", bn: "মেডিকেল ভ্রমণের জটিলতার বাস্তব সংখ্যা", fr: "Les vrais chiffres des complications du voyage médical", hi: "चिकित्सा यात्रा की जटिलताओं पर वास्तविक संख्याएँ", pt: "Números reais sobre complicações em viagem médica", ru: "Реальные цифры по осложнениям медицинских поездок", tr: "Tıbbi seyahat komplikasyonları hakkında gerçek sayılar" },
    e: { ar: "كم مرة يحدث شيء خطأ في الرعاية الطبية الدولية؟ نظرة صادقة على البيانات.", bn: "আন্তর্জাতিক চিকিৎসায় কতবার কিছু ভুল হয়? ডেটার একটি সৎ চিত্র।", fr: "À quelle fréquence quelque chose tourne mal en soins internationaux ? Un regard honnête sur les données.", hi: "अंतरराष्ट्रीय चिकित्सा देखभाल में कितनी बार कुछ गलत होता है? डेटा पर एक ईमानदार नज़र।", pt: "Com que frequência algo dá errado em cuidados médicos internacionais? Um olhar honesto sobre os dados.", ru: "Как часто что-то идёт не так в международной медицинской помощи? Честный взгляд на данные.", tr: "Uluslararası tıbbi bakımda bir şey ne sıklıkla ters gider? Verilere dürüst bir bakış." }
  },
  { id: 24,
    t: { ar: "ما الذي تمنّى المرضى لو كانوا يعرفونه قبل السفر الطبي", bn: "মেডিকেল ভ্রমণের আগে রোগীরা কী জানতে চাইতেন", fr: "Ce que les patients auraient aimé savoir avant leur voyage médical", hi: "मेडिकल ट्रैवल से पहले मरीज़ों ने क्या जानना चाहा होता", pt: "O que pacientes gostariam de saber antes da viagem médica", ru: "Что пациенты хотели бы знать до медицинской поездки", tr: "Hastaların tıbbi seyahatten önce bilmek istedikleri" },
    e: { ar: "مستخلص من 200+ مقابلة بعد الرحلة — أكثر لحظات \"كنت أتمنى لو كنت أعرف\" شيوعًا.", bn: "২০০+ ভ্রমণ-পরবর্তী রোগী সাক্ষাত্কার থেকে — সবচেয়ে সাধারণ 'আমি যদি জানতাম' মুহূর্তগুলি।", fr: "Extrait de 200+ entretiens patients post-trajet — les moments les plus fréquents de « j’aurais aimé savoir ».", hi: "200+ ट्रिप-पश्चात रोगी साक्षात्कारों से — सबसे आम 'काश मुझे पता होता' पल।", pt: "Extraído de 200+ entrevistas pós-viagem — os momentos mais comuns de 'eu queria ter sabido'.", ru: "Извлечено из более чем 200 интервью после поездок — самые частые моменты «жаль, что я не знал».", tr: "200+ seyahat sonrası hasta görüşmesinden — en yaygın 'keşke bilseydim' anları." }
  },
  { id: 25,
    t: { ar: "التكاليف الخفية للسفر الطبي، بنود مفصّلة", bn: "মেডিকেল ভ্রমণের গোপন খরচ, আইটেমাইজড", fr: "Les coûts cachés du voyage médical, ligne par ligne", hi: "चिकित्सा यात्रा की छिपी लागत, मद-वार", pt: "Os custos ocultos da viagem médica, item por item", ru: "Скрытые расходы медицинской поездки, по статьям", tr: "Tıbbi seyahatin gizli maliyetleri, kalem kalem" },
    e: { ar: "فوق سعر الإجراء: 14 بندًا تظهر في فواتير المرضى الفعلية لكنها نادرًا ما تدخل في التسعير الرئيسي.", bn: "প্রক্রিয়ার কোটের বাইরে: ১৪টি খরচ লাইন যা প্রকৃত রোগীর বিলে দেখা যায় কিন্তু খুব কমই হেডলাইন মূল্যে আসে।", fr: "Au-delà du devis : 14 postes qui apparaissent dans les factures patients mais rarement dans les prix annoncés.", hi: "प्रक्रिया कोट से परे: 14 लागत लाइनें जो वास्तविक रोगी बिलों में दिखती हैं लेकिन हेडलाइन मूल्य में शायद ही कभी आती हैं।", pt: "Além do orçamento do procedimento: 14 linhas de custo que aparecem em contas reais mas raramente entram no preço de manchete.", ru: "Сверх цены процедуры: 14 статей расходов, которые появляются в реальных счетах пациентов, но редко входят в заглавную цену.", tr: "Prosedür teklifinin ötesinde: gerçek hasta faturalarında görünen ancak nadiren manşet fiyatına giren 14 maliyet kalemi." }
  },
  { id: 26,
    t: { ar: "كيف تقارن العروض من ثلاث مستشفيات", bn: "তিনটি হাসপাতাল থেকে কোটেশন কীভাবে তুলনা করবেন", fr: "Comment comparer trois devis hospitaliers", hi: "तीन अस्पतालों के कोटेशन की तुलना कैसे करें", pt: "Como comparar orçamentos de três hospitais", ru: "Как сравнить предложения от трёх больниц", tr: "Üç hastane teklifini nasıl karşılaştırılır" },
    e: { ar: "إطار جنبًا إلى جنب لتقييم العروض من برامج دولية متعددة — يتجاوز السعر الرئيسي.", bn: "একাধিক আন্তর্জাতিক প্রোগ্রাম থেকে অফার মূল্যায়নের জন্য একটি পাশাপাশি কাঠামো — শুধু হেডলাইন মূল্যের বাইরে।", fr: "Un cadre côte à côte pour évaluer les offres de plusieurs programmes internationaux — au-delà du prix annoncé.", hi: "कई अंतरराष्ट्रीय कार्यक्रमों के ऑफ़र का मूल्यांकन करने के लिए एक साइड-बाय-साइड फ्रेमवर्क — सिर्फ हेडलाइन मूल्य से परे।", pt: "Um framework lado a lado para avaliar ofertas de múltiplos programas internacionais — além do preço de manchete.", ru: "Параллельная схема для оценки предложений нескольких международных программ — не только заголовочная цена.", tr: "Birden fazla uluslararası programdan gelen teklifleri değerlendirmek için yan yana bir çerçeve — sadece manşet fiyatın ötesinde." }
  },
  { id: 27,
    t: { ar: "هل السياحة الطبية قابلة للخصم الضريبي؟ نظرة مفصّلة", bn: "মেডিকেল ট্যুরিজম কি কর-কর্তনযোগ্য? একটি বিস্তারিত দৃষ্টিভঙ্গি", fr: "Le tourisme médical est-il déductible des impôts ? Examen détaillé", hi: "क्या मेडिकल टूरिज़्म कर-कटौती योग्य है? एक विस्तृत नज़र", pt: "Turismo médico é dedutível do imposto? Um olhar detalhado", ru: "Можно ли вычесть медицинский туризм из налогов? Подробный обзор", tr: "Tıbbi turizm vergiden düşülebilir mi? Ayrıntılı bir bakış" },
    e: { ar: "ما يمكن لمرضى الولايات المتحدة وبريطانيا والاتحاد الأوروبي وكندا خصمه فعلًا، مع متطلبات التوثيق والأخطاء الشائعة.", bn: "US, UK, EU, এবং কানাডিয়ান রোগীরা আসলে কী কর্তন করতে পারেন, ডকুমেন্টেশন প্রয়োজনীয়তা এবং সাধারণ ভুল সহ।", fr: "Ce que les patients US, UK, UE et canadiens peuvent réellement déduire, avec exigences documentaires et erreurs courantes.", hi: "US, UK, EU, और कनाडाई मरीज़ वास्तव में क्या कटौती कर सकते हैं, दस्तावेज़ीकरण आवश्यकताओं और सामान्य गलतियों के साथ।", pt: "O que pacientes dos EUA, UK, UE e Canadá podem realmente deduzir, com requisitos de documentação e erros comuns.", ru: "Что реально могут вычесть пациенты США, Великобритании, ЕС и Канады, с требованиями к документам и типичными ошибками.", tr: "ABD, Birleşik Krallık, AB ve Kanada hastalarının gerçekten neyi düşebileceği, belgeleme gereksinimleri ve yaygın hatalar." }
  },
  { id: 28,
    t: { ar: "التكلفة الحقيقية لعلاج السرطان في الخارج", bn: "বিদেশে ক্যান্সার চিকিৎসার প্রকৃত খরচ", fr: "Le vrai coût d’un traitement du cancer à l’étranger", hi: "विदेश में कैंसर उपचार की वास्तविक लागत", pt: "O custo real do tratamento de câncer no exterior", ru: "Реальная стоимость лечения рака за рубежом", tr: "Yurt dışında kanser tedavisinin gerçek maliyeti" },
    e: { ar: "أبعد من سعر دورة العلاج الكيميائي: التصوير، الإقامة، الرعاية الداعمة، والقوس السنوي الذي يحدد التكلفة الإجمالية الحقيقية.", bn: "কেমো সাইকেল কোটের বাইরে: ইমেজিং, হাসপাতালে ভর্তি, সহায়ক যত্ন, এবং বছরব্যাপী আর্ক যা প্রকৃত মোট খরচ নির্ধারণ করে।", fr: "Au-delà du prix d’un cycle de chimio : imagerie, hospitalisation, soins de support, et l’arc d’un an qui détermine le coût total réel.", hi: "केमो साइकल कोट से परे: इमेजिंग, अस्पताल में भर्ती, सहायक देखभाल, और साल भर का चाप जो वास्तविक कुल लागत निर्धारित करता है।", pt: "Além do orçamento por ciclo de quimio: imagem, internação, cuidados de suporte e o arco anual que determina o custo total real.", ru: "Помимо стоимости цикла химиотерапии: визуализация, госпитализация, поддерживающее лечение и годовой контур, определяющий реальную общую стоимость.", tr: "Kemo siklus teklifinin ötesinde: görüntüleme, hastane yatışı, destekleyici bakım ve gerçek toplam maliyeti belirleyen bir yıllık eğri." }
  },
  { id: 29,
    t: { ar: "توفير 50,000$ على الرعاية الطبية: مسارات واقعية", bn: "চিকিৎসা যত্নে $50k সাশ্রয়: বাস্তব পথ", fr: "Économiser 50 000 $ sur les soins médicaux : voies réalistes", hi: "चिकित्सा देखभाल पर $50k बचाना: यथार्थवादी रास्ते", pt: "Economizar US$ 50 mil em cuidados médicos: caminhos realistas", ru: "Экономия 50 000 $ на медицинской помощи: реалистичные пути", tr: "Tıbbi bakımda 50 bin $ tasarruf: gerçekçi yollar" },
    e: { ar: "خمس فئات من الإجراءات حيث ينتج السفر الدولي وفورات قابلة للتكرار وذات معنى — وثلاث لا تنتجها.", bn: "পাঁচটি প্রক্রিয়া বিভাগ যেখানে আন্তর্জাতিক ভ্রমণ অর্থপূর্ণ, পুনরাবৃত্তিযোগ্য সাশ্রয় তৈরি করে — এবং তিনটি যেখানে করে না।", fr: "Cinq catégories d’interventions où le voyage international génère des économies réelles et reproductibles — et trois où ce n’est pas le cas.", hi: "पाँच प्रक्रिया श्रेणियाँ जहाँ अंतरराष्ट्रीय यात्रा सार्थक, दोहराने योग्य बचत उत्पन्न करती है — और तीन जहाँ नहीं करती।", pt: "Cinco categorias de procedimentos onde a viagem internacional gera economias significativas e repetíveis — e três onde não.", ru: "Пять категорий процедур, где международная поездка даёт значимую и воспроизводимую экономию — и три, где нет.", tr: "Uluslararası seyahatin anlamlı, tekrarlanabilir tasarruf ürettiği beş prosedür kategorisi — ve üretmediği üç kategori." }
  },
  { id: 30,
    t: { ar: "التفاوض على العروض الطبية الدولية (دون حرق الجسور)", bn: "আন্তর্জাতিক চিকিৎসা কোটেশন আলোচনা (সেতু না পুড়িয়ে)", fr: "Négocier les devis médicaux internationaux (sans brûler les ponts)", hi: "अंतरराष्ट्रीय चिकित्सा कोटेशन पर बातचीत (पुल जलाए बिना)", pt: "Negociar orçamentos médicos internacionais (sem queimar pontes)", ru: "Переговоры по международным медицинским предложениям (не сжигая мосты)", tr: "Uluslararası tıbbi teklifleri pazarlık etme (köprüleri yakmadan)" },
    e: { ar: "معظم العروض الطبية الدولية تحتمل مرونة 10-25%. كيف تطلبها دون أن يصبح البرنامج أقل التزامًا برعايتك.", bn: "বেশিরভাগ আন্তর্জাতিক চিকিৎসা কোটেশনে ১০-২৫% নমনীয়তা থাকে। কীভাবে অনুরোধ করবেন যাতে প্রোগ্রাম আপনার যত্নে কম বিনিয়োগ না করে।", fr: "La plupart des devis médicaux internationaux ont 10 à 25 % de marge. Comment la demander sans rendre le programme moins investi dans vos soins.", hi: "अधिकांश अंतरराष्ट्रीय चिकित्सा कोटेशनों में 10-25% लचीलापन होता है। इसे कैसे मांगें ताकि कार्यक्रम आपकी देखभाल में कम निवेशित न हो।", pt: "A maioria dos orçamentos médicos internacionais tem 10-25% de flexibilidade. Como pedir sem fazer o programa se importar menos com seu cuidado.", ru: "У большинства международных медицинских предложений есть запас 10-25%. Как просить его, не снижая заинтересованность программы в вашем лечении.", tr: "Çoğu uluslararası tıbbi teklifte %10-25 esneklik vardır. Programın bakımınıza daha az yatırım yapmasına neden olmadan nasıl talep edilir." }
  },
];

async function main() {
  let inserted = 0, updated = 0;
  for (const p of POSTS) {
    for (const locale of LOCALES) {
      for (const [field, value] of [["title", p.t[locale]], ["excerpt", p.e[locale]]] as const) {
        const result = await db.execute(sql`
          INSERT INTO translations (translatable_type, translatable_id, locale, field_name, value,
                                    is_machine_translated, is_reviewed, reviewed_by, reviewed_at)
          VALUES ('blog_post', ${p.id}, ${locale}, ${field}, ${value}, false, true, 'manual-wave2.20a', NOW())
          ON CONFLICT (translatable_type, translatable_id, locale, field_name)
          DO UPDATE SET value = EXCLUDED.value, is_machine_translated = false, is_reviewed = true,
                        reviewed_by = 'manual-wave2.20a', reviewed_at = NOW(), updated_at = NOW()
          RETURNING (xmax = 0) AS inserted
        `);
        const row = Array.from(result as any)[0] as any;
        if (row?.inserted) inserted++; else updated++;
      }
    }
  }
  console.log(`Wave 2.20a complete: inserted=${inserted} updated=${updated}`);
  console.log(`Total: ${inserted + updated} (${POSTS.length} posts × ${LOCALES.length} locales × 2 fields)`);
  process.exit(0);
}
main().catch((e) => { console.error(e); process.exit(1); });
