/**
 * Wave 2.20b — final 31 blog posts (IDs 31-61) × 7 locales × 2 fields = 434 strings.
 * Closes the blog title+excerpt translation gap. Body content stays EN.
 */
import { db } from "../src/lib/db";
import { sql } from "drizzle-orm";

type Locale = "ar" | "bn" | "fr" | "hi" | "pt" | "ru" | "tr";
const LOCALES: Locale[] = ["ar", "bn", "fr", "hi", "pt", "ru", "tr"];

interface B { id: number; t: Record<Locale, string>; e: Record<Locale, string>; }

const POSTS: B[] = [
  { id: 31,
    t: { ar: "هل أحتاج إلى جراحة السمنة؟ إطار قرار صادق", bn: "আমার কি ব্যারিয়াট্রিক সার্জারি দরকার? একটি সৎ সিদ্ধান্ত কাঠামো", fr: "Faut-il une chirurgie bariatrique ? Un cadre de décision honnête", hi: "क्या मुझे बैरिएट्रिक सर्जरी करानी चाहिए? एक ईमानदार निर्णय फ्रेम", pt: "Devo fazer cirurgia bariátrica? Um framework honesto", ru: "Нужна ли мне бариатрическая операция? Честная рамка решения", tr: "Bariatrik cerrahi olmalı mıyım? Dürüst bir karar çerçevesi" },
    e: { ar: "جراحة السمنة فعّالة جدًا للمريض المناسب، لكنها تُوصى بشكل مفرط في بعض الحالات. كيف تقيّم.", bn: "সঠিক রোগীর জন্য ব্যারিয়াট্রিক সার্জারি অত্যন্ত কার্যকর, তবে কিছু ক্ষেত্রে অত্যধিক প্রস্তাবিত। কীভাবে মূল্যায়ন করবেন।", fr: "La chirurgie bariatrique est très efficace pour le bon patient, mais sur-recommandée parfois. Comment évaluer.", hi: "सही मरीज़ के लिए बैरिएट्रिक सर्जरी अत्यधिक प्रभावी है, लेकिन कुछ मामलों में अति-अनुशंसित। मूल्यांकन कैसे करें।", pt: "Cirurgia bariátrica é altamente eficaz para o paciente certo, mas super-recomendada em alguns casos. Como avaliar.", ru: "Бариатрическая хирургия очень эффективна для подходящего пациента, но в некоторых случаях её рекомендуют избыточно. Как оценить.", tr: "Bariatrik cerrahi doğru hasta için son derece etkilidir, ancak bazı durumlarda fazla önerilir. Nasıl değerlendirilir." }
  },
  { id: 32,
    t: { ar: "علاج الخصوبة: متى تتوقف، متى تغيّر المسار", bn: "ফার্টিলিটি চিকিৎসা: কখন থামবেন, কখন পরিবর্তন করবেন", fr: "Traitement de fertilité : quand s’arrêter, quand changer de cap", hi: "प्रजनन उपचार: कब रुकें, कब रास्ता बदलें", pt: "Tratamento de fertilidade: quando parar, quando mudar", ru: "Лечение бесплодия: когда остановиться, когда изменить курс", tr: "Fertilite tedavisi: ne zaman durmalı, ne zaman değişmeli" },
    e: { ar: "نقاط قرار في أطفال الأنابيب يفوّتها المرضى غالبًا — بما في ذلك متى يصبح الإصرار خيارًا خاطئًا.", bn: "আইভিএফে সিদ্ধান্তের পয়েন্ট যা রোগীরা প্রায়ই মিস করেন — কখন অধ্যবসায় ভুল পছন্দ হয়ে যায় তা সহ।", fr: "Des points de décision en FIV souvent ignorés — y compris quand persister devient le mauvais choix.", hi: "आईवीएफ में निर्णय बिंदु जिन्हें मरीज़ अक्सर मिस करते हैं — जिसमें कब बने रहना गलत विकल्प बन जाता है।", pt: "Pontos de decisão em FIV que pacientes frequentemente perdem — incluindo quando persistir se torna a escolha errada.", ru: "Точки решений в ЭКО, которые пациенты часто упускают — включая момент, когда продолжать становится ошибкой.", tr: "Hastaların sıklıkla kaçırdığı IVF karar noktaları — ısrar etmenin yanlış seçim olduğu zaman dahil." }
  },
  { id: 33,
    t: { ar: "متبرّع حي مقابل متوفى للزراعة: كيف تقرر", bn: "জীবিত বনাম মৃত দাতা ট্রান্সপ্ল্যান্ট: কীভাবে সিদ্ধান্ত নেবেন", fr: "Greffe à donneur vivant ou décédé : comment décider", hi: "जीवित बनाम मृत दाता प्रत्यारोपण: कैसे तय करें", pt: "Transplante de doador vivo vs falecido: como decidir", ru: "Трансплантация от живого vs умершего донора: как решить", tr: "Canlı vs ölmüş donör nakli: nasıl karar verilir" },
    e: { ar: "لكلٍّ من زراعة الكلى والكبد، يقدّم المتبرع الحي نتائج أفضل — لكن جانب المتبرع له اعتباراته.", bn: "কিডনি ও লিভার উভয় ট্রান্সপ্ল্যান্টের জন্য জীবিত-দাতা ভাল ফলাফল দেয় — তবে দাতার দিকে নিজস্ব বিবেচনা আছে।", fr: "Pour les greffes de rein et de foie, le donneur vivant offre de meilleurs résultats — mais le côté donneur a ses propres considérations.", hi: "गुर्दा और लीवर दोनों प्रत्यारोपण के लिए जीवित-दाता बेहतर परिणाम देता है — लेकिन दाता पक्ष की अपनी विचारणाएँ हैं।", pt: "Para transplantes de rim e fígado, doador vivo oferece melhores resultados — mas o lado do doador tem suas próprias considerações.", ru: "Для трансплантации почки и печени живой донор даёт лучшие исходы — но у донора своя сторона вопроса.", tr: "Hem böbrek hem karaciğer nakli için canlı donör daha iyi sonuçlar verir — ancak donör tarafının kendi değerlendirmeleri vardır." }
  },
  { id: 34,
    t: { ar: "هل أختار الجراحة الروبوتية؟", bn: "আমি কি রোবোটিক সার্জারি বেছে নেব?", fr: "Faut-il choisir la chirurgie robotique ?", hi: "क्या मुझे रोबोटिक सर्जरी चुननी चाहिए?", pt: "Devo escolher cirurgia robótica?", ru: "Стоит ли выбирать роботическую хирургию?", tr: "Robotik cerrahi seçmeli miyim?" },
    e: { ar: "الجراحة الروبوتية معيار الآن لبعض الإجراءات وتسويق لأخرى. كيف تقيّم ما إذا كانت مناسبة لحالتك.", bn: "রোবোটিক সার্জারি এখন কিছু পদ্ধতির জন্য মান এবং অন্যদের জন্য বিপণন। আপনার ক্ষেত্রে এটি সঠিক কিনা কীভাবে মূল্যায়ন করবেন।", fr: "La chirurgie robotique est désormais standard pour certaines interventions, marketing pour d’autres. Comment évaluer si c’est adapté à votre cas.", hi: "रोबोटिक सर्जरी अब कुछ प्रक्रियाओं के लिए मानक है और अन्य के लिए मार्केटिंग। आपके मामले के लिए सही है या नहीं इसका मूल्यांकन कैसे करें।", pt: "Cirurgia robótica agora é padrão para alguns procedimentos e marketing para outros. Como avaliar se é certa para seu caso.", ru: "Роботическая хирургия теперь стандарт для некоторых процедур и маркетинг для других. Как оценить, подходит ли она вашему случаю.", tr: "Robotik cerrahi artık bazı prosedürler için standart, diğerleri için pazarlama. Sizin vakanız için doğru olup olmadığı nasıl değerlendirilir." }
  },
  { id: 35,
    t: { ar: "الجراحة التجميلية في الخارج: إطار قرار", bn: "বিদেশে কসমেটিক সার্জারি: একটি সিদ্ধান্ত কাঠামো", fr: "Chirurgie esthétique à l’étranger : un cadre de décision", hi: "विदेश में कॉस्मेटिक सर्जरी: एक निर्णय फ्रेम", pt: "Cirurgia estética no exterior: um framework de decisão", ru: "Эстетическая хирургия за рубежом: рамка решения", tr: "Yurt dışında estetik cerrahi: bir karar çerçevesi" },
    e: { ar: "الإجراءات التجميلية في الخارج شائعة وعالية المخاطر. كيف تقيّم ما إذا كانت الوفورات تبرّر التنازلات.", bn: "বিদেশে কসমেটিক প্রক্রিয়া জনপ্রিয় ও উচ্চ-ঝুঁকির। সাশ্রয় কীভাবে ট্রেড-অফ ন্যায্যতা দেয় তা মূল্যায়ন করুন।", fr: "Les interventions esthétiques à l’étranger sont populaires et risquées. Comment évaluer si les économies justifient les compromis.", hi: "विदेश में कॉस्मेटिक प्रक्रियाएँ लोकप्रिय और उच्च-जोखिम वाली हैं। बचत क्या ट्रेड-ऑफ़ को सही ठहराती है इसका मूल्यांकन कैसे करें।", pt: "Procedimentos estéticos no exterior são populares e de alto risco. Como avaliar se a economia justifica os compromissos.", ru: "Эстетические процедуры за рубежом популярны и рискованны. Как оценить, оправдывает ли экономия компромиссы.", tr: "Yurt dışı estetik prosedürleri popüler ve yüksek risklidir. Tasarrufların ödünlere değip değmediği nasıl değerlendirilir." }
  },
  { id: 36,
    t: { ar: "علاج الخصوبة مقابل التبني: منظور", bn: "ফার্টিলিটি চিকিৎসা বনাম দত্তক: একটি দৃষ্টিভঙ্গি", fr: "Traitement de fertilité ou adoption : une perspective", hi: "प्रजनन उपचार बनाम गोद लेना: एक परिप्रेक्ष्य", pt: "Tratamento de fertilidade vs adoção: uma perspectiva", ru: "Лечение бесплодия vs усыновление: перспектива", tr: "Fertilite tedavisi vs evlat edinme: bir perspektif" },
    e: { ar: "عندما لا يعمل علاج الخصوبة، البديل ليس فقط التوقف. نظرة صريحة على التبني كمسار موازٍ.", bn: "যখন ফার্টিলিটি চিকিৎসা কাজ করছে না, বিকল্প শুধু থামা নয়। দত্তককে সমান্তরাল পথ হিসেবে একটি অকপট দেখা।", fr: "Quand la FIV ne fonctionne pas, l’alternative n’est pas seulement d’arrêter. Un regard franc sur l’adoption comme voie parallèle.", hi: "जब फर्टिलिटी उपचार काम नहीं कर रहा, विकल्प सिर्फ रुकना नहीं है। समानांतर पथ के रूप में गोद लेने पर ईमानदार नज़र।", pt: "Quando o tratamento de fertilidade não funciona, a alternativa não é só parar. Um olhar franco sobre adoção como caminho paralelo.", ru: "Когда лечение бесплодия не работает, альтернатива — не только остановиться. Прямой взгляд на усыновление как параллельный путь.", tr: "Fertilite tedavisi işe yaramadığında alternatif sadece durmak değildir. Paralel yol olarak evlat edinmeye dürüst bir bakış." }
  },
  { id: 37,
    t: { ar: "هل أُجري جراحة تصحيحية؟", bn: "আমি কি রিভিশনাল সার্জারি করাব?", fr: "Faut-il une chirurgie de révision ?", hi: "क्या मुझे रिविज़नल सर्जरी करानी चाहिए?", pt: "Devo fazer cirurgia revisional?", ru: "Делать ли ревизионную операцию?", tr: "Revizyonel cerrahi olmalı mıyım?" },
    e: { ar: "الجراحة التصحيحية — إصلاح إجراء سابق — أصعب تقنيًا، أكثر خطورة، ونادرًا ما تستحق نفس النقاش كالجراحة الأولية.", bn: "রিভিশনাল সার্জারি — পূর্ববর্তী প্রক্রিয়া ঠিক করা — প্রযুক্তিগতভাবে কঠিন, ঝুঁকিপূর্ণ, এবং প্রাথমিক সার্জারির মতো একই কথোপকথনের যোগ্য না।", fr: "La chirurgie de révision — réparer une intervention précédente — est techniquement plus difficile, plus risquée et mérite rarement la même discussion que la chirurgie primaire.", hi: "रिविज़नल सर्जरी — पिछली प्रक्रिया को ठीक करना — तकनीकी रूप से कठिन, जोखिम भरा, और प्राथमिक सर्जरी जैसी ही चर्चा के लायक शायद ही है।", pt: "Cirurgia revisional — consertar um procedimento anterior — é tecnicamente mais difícil, mais arriscada e raramente merece a mesma conversa que cirurgia primária.", ru: "Ревизионная операция — исправление предыдущей — технически сложнее, рискованнее и редко заслуживает той же дискуссии, что и первичная.", tr: "Revizyonel cerrahi — önceki bir prosedürü düzeltmek — teknik olarak daha zor, daha riskli ve nadiren birincil cerrahi ile aynı tartışmayı hak eder." }
  },
  { id: 38,
    t: { ar: "هل أجري جراحة اختيارية في زمن عدم اليقين الاقتصادي؟", bn: "অর্থনৈতিক অনিশ্চয়তায় কি ঐচ্ছিক সার্জারি করব?", fr: "Faire une chirurgie élective en période d’incertitude économique ?", hi: "क्या आर्थिक अनिश्चितता के दौरान वैकल्पिक सर्जरी करवानी चाहिए?", pt: "Devo fazer cirurgia eletiva durante incerteza econômica?", ru: "Делать ли плановую операцию во времена экономической неопределённости?", tr: "Ekonomik belirsizlikte elektif cerrahi olmalı mıyım?" },
    e: { ar: "تغيرات التعريفات وتقلبات العملة والتحولات الاقتصادية تعقّد قرارات السفر الطبي. كيف تفكّر في التوقيت.", bn: "ট্যারিফ পরিবর্তন, মুদ্রা অস্থিরতা এবং অর্থনৈতিক পরিবর্তন মেডিকেল-ভ্রমণ সিদ্ধান্তকে জটিল করে। সময় সম্পর্কে কীভাবে ভাববেন।", fr: "Changements tarifaires, volatilité des devises et bouleversements économiques compliquent les décisions de voyage médical. Comment penser au timing.", hi: "टैरिफ परिवर्तन, मुद्रा अस्थिरता, और आर्थिक बदलाव चिकित्सा-यात्रा निर्णयों को जटिल बनाते हैं। समय के बारे में कैसे सोचें।", pt: "Mudanças tarifárias, volatilidade cambial e mudanças econômicas complicam decisões de viagem médica. Como pensar no tempo.", ru: "Изменения тарифов, валютная волатильность и экономические сдвиги усложняют решения о медицинских поездках. Как думать о тайминге.", tr: "Tarife değişiklikleri, döviz oynaklığı ve ekonomik değişimler tıbbi seyahat kararlarını karmaşıklaştırır. Zamanlama hakkında nasıl düşünülür." }
  },
  { id: 39,
    t: { ar: "كيف يبدو التعافي الجيد يومًا بيوم", bn: "ভাল পুনরুদ্ধার দিন-প্রতিদিন কেমন দেখায়", fr: "À quoi ressemble une bonne récupération, jour après jour", hi: "अच्छी रिकवरी दिन-प्रतिदिन कैसी दिखती है", pt: "Como é uma boa recuperação, dia a dia", ru: "Как выглядит хорошее восстановление день за днём", tr: "İyi bir iyileşme gün gün nasıl görünür" },
    e: { ar: "نافذة 30 يومًا بعد الجراحة، مفصّلة إلى ما هو طبيعي، ما يستحق الإبلاغ، وما يجب أن يُحفز إجراءً فوريًا.", bn: "সার্জারির পর ৩০ দিনের একটি জানালা, ভাঙা: কী স্বাভাবিক, কী রিপোর্ট করার মতো, এবং কী তাত্ক্ষণিক পদক্ষেপ ট্রিগার করা উচিত।", fr: "Une fenêtre de 30 jours après l’opération, détaillée : ce qui est normal, ce qui mérite signalement, ce qui doit déclencher une action immédiate.", hi: "सर्जरी के बाद 30-दिन की खिड़की, विभाजित: क्या सामान्य है, क्या ध्वजांकित करने योग्य है, और क्या तत्काल कार्रवाई शुरू करनी चाहिए।", pt: "Uma janela de 30 dias após a cirurgia, detalhada em: o que é normal, o que vale sinalizar, e o que deve disparar ação imediata.", ru: "30-дневное окно после операции, разбитое на: что нормально, что стоит флагировать, что должно вызвать немедленные действия.", tr: "Ameliyattan sonraki 30 günlük pencere, neyin normal olduğu, neyin işaretlenmesi gerektiği ve neyin acil eylem tetiklemesi gerektiği şeklinde bölünmüş." }
  },
  { id: 40,
    t: { ar: "إدارة المشاعر بعد جراحة كبرى", bn: "বড় সার্জারির পর আবেগ পরিচালনা", fr: "Gérer ses émotions après une opération majeure", hi: "बड़ी सर्जरी के बाद भावनाओं का प्रबंधन", pt: "Gerenciar emoções após cirurgia maior", ru: "Управление эмоциями после серьёзной операции", tr: "Büyük ameliyattan sonra duyguları yönetme" },
    e: { ar: "الاكتئاب ما بعد العملية، القلق، وأسئلة الهوية شائعة لكنها نادرًا ما تُناقش. المشهد الصادق.", bn: "পোস্ট-অপ ডিপ্রেশন, উদ্বেগ এবং পরিচয় প্রশ্ন সাধারণ কিন্তু খুব কমই আলোচিত। সৎ ভূদৃশ্য।", fr: "Dépression post-opératoire, anxiété et questions d’identité sont fréquentes mais rarement abordées. Le paysage honnête.", hi: "पोस्ट-ऑप अवसाद, चिंता, और पहचान प्रश्न आम हैं लेकिन शायद ही कभी चर्चा की जाती है। ईमानदार परिदृश्य।", pt: "Depressão pós-op, ansiedade e questões de identidade são comuns mas raramente discutidas. O panorama honesto.", ru: "Послеоперационная депрессия, тревога и вопросы идентичности часты, но редко обсуждаются. Честный ландшафт.", tr: "Ameliyat sonrası depresyon, anksiyete ve kimlik soruları yaygın ancak nadiren tartışılır. Dürüst manzara." }
  },
  { id: 41,
    t: { ar: "الأسبوع الذي تعود فيه إلى بلدك: قائمة مرجعية مفصّلة", bn: "যে সপ্তাহে আপনি বাড়ি ফিরবেন: একটি বিস্তারিত চেকলিস্ট", fr: "La semaine du retour : une checklist détaillée", hi: "जब आप घर लौटें वो सप्ताह: एक विस्तृत चेकलिस्ट", pt: "A semana em que você volta para casa: um checklist detalhado", ru: "Неделя возвращения домой: подробный чек-лист", tr: "Eve uçtuğunuz hafta: ayrıntılı bir kontrol listesi" },
    e: { ar: "ما يجب التعامل معه في الـ5-7 أيام قبل المغادرة: المستندات، الأدوية، المتابعة، الطوارئ. لا تترك الوجهة وأنت تنقص أشياء.", bn: "ছাড়ার ৫-৭ দিন আগে কী পরিচালনা করবেন: নথি, ওষুধ, ফলো-আপ, কন্টিনজেন্সি। জিনিসপত্র মিস না করে গন্তব্য ছাড়ুন।", fr: "Ce qu’il faut gérer 5–7 jours avant le départ : documents, médicaments, suivi, contingences. Ne quittez pas la destination en oubliant des choses.", hi: "प्रस्थान से 5-7 दिन पहले क्या संभालें: दस्तावेज़, दवाएँ, फॉलो-अप, आकस्मिकताएँ। चीज़ें मिस करके गंतव्य न छोड़ें।", pt: "O que cuidar nos 5-7 dias antes da partida: documentos, medicações, seguimento, contingência. Não deixe o destino faltando coisas.", ru: "Что сделать за 5-7 дней до отъезда: документы, лекарства, наблюдение, план на случай ЧП. Не уезжайте, забыв что-то.", tr: "Ayrılmadan 5-7 gün önce halletmeniz gerekenler: belgeler, ilaçlar, takip, beklenmedik durumlar. Eksik bırakarak destinasyondan ayrılmayın." }
  },
  { id: 42,
    t: { ar: "إدارة الألم بعد الجراحة دون الإفراط في المسكنات الأفيونية", bn: "ওপিওইড অতিরিক্ত ব্যবহার ছাড়াই সার্জারির পর ব্যথা পরিচালনা", fr: "Gérer la douleur post-op sans abuser des opioïdes", hi: "ओपिओइड का अति प्रयोग किए बिना सर्जरी के बाद दर्द का प्रबंधन", pt: "Gerenciar dor pós-op sem exagerar em opioides", ru: "Управление послеоперационной болью без злоупотребления опиоидами", tr: "Opioid abartmadan ameliyat sonrası ağrı yönetimi" },
    e: { ar: "تسكين متعدد الأنماط، متى تخفّض الجرعة، والواقع الصادق لألم ما بعد العملية.", bn: "মাল্টিমোডাল অ্যানালজেসিয়া, কখন টেপার করবেন, এবং পোস্ট-অপ ব্যথার সৎ বাস্তবতা।", fr: "Analgésie multimodale, quand diminuer les doses, et la réalité honnête de la douleur post-op.", hi: "बहुविधि एनाल्जेसिया, कब टेपर करें, और पोस्ट-ऑप दर्द की ईमानदार वास्तविकता।", pt: "Analgesia multimodal, quando reduzir, e a realidade honesta da dor pós-op.", ru: "Мультимодальная анальгезия, когда снижать дозу, и честная реальность послеоперационной боли.", tr: "Multimodal analjezi, ne zaman azaltılmalı ve ameliyat sonrası ağrının dürüst gerçekliği." }
  },
  { id: 43,
    t: { ar: "ماذا لو احتجت إلى مراجعة بعد العودة إلى البلد؟", bn: "বাড়ি ফেরার পর যদি রিভিশনের প্রয়োজন হয়?", fr: "Et si j’ai besoin d’une révision après mon retour ?", hi: "अगर मुझे घर लौटने के बाद रिविज़न की ज़रूरत हो तो?", pt: "E se eu precisar de revisão depois de voltar para casa?", ru: "Что, если мне понадобится ревизия после возвращения домой?", tr: "Eve döndükten sonra revizyona ihtiyacım olursa?" },
    e: { ar: "عند تطور مضاعفة أو نتيجة غير مُحقّقة بعد أسابيع أو أشهر من الجراحة الدولية — خياراتك وما تتوقعه.", bn: "আন্তর্জাতিক সার্জারির পর সপ্তাহ বা মাসের মধ্যে জটিলতা বা অপ্রাপ্ত ফলাফল দেখা দিলে — আপনার বিকল্প এবং কী আশা করবেন।", fr: "Quand une complication ou un résultat insatisfaisant apparaît des semaines ou des mois après l’intervention internationale — vos options et à quoi s’attendre.", hi: "अंतरराष्ट्रीय सर्जरी के सप्ताह या महीनों बाद जटिलता या अप्राप्त परिणाम विकसित होने पर — आपके विकल्प और क्या अपेक्षा करें।", pt: "Quando uma complicação ou resultado não alcançado se desenvolve semanas ou meses após cirurgia internacional — suas opções e o que esperar.", ru: "Когда осложнение или недостигнутый результат развивается через недели или месяцы после международной операции — ваши варианты и чего ожидать.", tr: "Uluslararası cerrahiden haftalar veya aylar sonra bir komplikasyon veya elde edilemeyen sonuç gelişirse — seçenekleriniz ve beklenenler." }
  },
  { id: 44,
    t: { ar: "السجلات الطبية الدولية: تنظيم كل شيء", bn: "আন্তর্জাতিক মেডিকেল রেকর্ড: সবকিছু সংগঠিত রাখা", fr: "Dossiers médicaux internationaux : tout garder organisé", hi: "अंतरराष्ट्रीय चिकित्सा रिकॉर्ड: सब कुछ व्यवस्थित रखना", pt: "Prontuários médicos internacionais: mantendo tudo organizado", ru: "Международные медицинские записи: всё в порядке", tr: "Uluslararası tıbbi kayıtlar: her şeyi düzenli tutmak" },
    e: { ar: "نظام عملي لإدارة جبل الوثائق الذي يأتي مع الرعاية الطبية الدولية، قبل وأثناء وبعد.", bn: "আন্তর্জাতিক চিকিৎসা যত্নের সাথে আসা ডকুমেন্ট-পাহাড় পরিচালনার জন্য একটি ব্যবহারিক সিস্টেম, আগে, সময় ও পরে।", fr: "Un système pratique pour gérer la montagne de documents liée aux soins internationaux, avant, pendant et après.", hi: "अंतरराष्ट्रीय चिकित्सा देखभाल के साथ आने वाले दस्तावेज़-पहाड़ को प्रबंधित करने के लिए एक व्यावहारिक प्रणाली, पहले, दौरान और बाद में।", pt: "Um sistema prático para gerenciar a montanha de documentos que vem com cuidado médico internacional, antes, durante e depois.", ru: "Практическая система для управления горой документов международной медицинской помощи — до, во время и после.", tr: "Uluslararası tıbbi bakımla gelen belge dağını yönetmek için pratik bir sistem, öncesi, sırası ve sonrası." }
  },
  { id: 45,
    t: { ar: "ما الأسئلة التي يجب طرحها على البرنامج قبل السفر", bn: "ভ্রমণের আগে প্রোগ্রামকে কী প্রশ্ন করবেন", fr: "Quelles questions poser au programme avant de partir", hi: "उड़ान से पहले कार्यक्रम से क्या प्रश्न पूछें", pt: "Que perguntas fazer ao programa antes de viajar", ru: "Какие вопросы задать программе перед вылетом", tr: "Uçmadan önce programa hangi soruları sormalı" },
    e: { ar: "30 سؤالًا محددًا يجب أن يُجاب لكل مريض قبل الالتزام بجراحة دولية — بالفئة والأولوية.", bn: "৩০টি নির্দিষ্ট প্রশ্ন যা প্রতিটি রোগীর আন্তর্জাতিক সার্জারিতে প্রতিশ্রুতি দেওয়ার আগে উত্তর পেতে হবে — বিভাগ ও অগ্রাধিকার অনুসারে।", fr: "30 questions précises à se faire répondre avant de s’engager dans une opération internationale — par catégorie et priorité.", hi: "30 विशिष्ट प्रश्न जिनका उत्तर हर मरीज़ को अंतरराष्ट्रीय सर्जरी के लिए प्रतिबद्ध होने से पहले मिलना चाहिए — श्रेणी और प्राथमिकता द्वारा।", pt: "30 perguntas específicas que todo paciente deve ter respondidas antes de se comprometer com cirurgia internacional — por categoria e prioridade.", ru: "30 конкретных вопросов, на которые каждый пациент должен получить ответ до согласия на международную операцию — по категориям и приоритету.", tr: "Her hastanın uluslararası cerrahiye karar vermeden önce yanıt alması gereken 30 spesifik soru — kategori ve önceliğe göre." }
  },
  { id: 46,
    t: { ar: "تكلفة استبدال الركبة: الهند مقابل تايلاند مقابل تركيا، بصراحة", bn: "হাঁটু প্রতিস্থাপন খরচ: ভারত বনাম থাইল্যান্ড বনাম তুরস্ক, সততার সাথে", fr: "Coût de la prothèse du genou : Inde, Thaïlande, Turquie, honnêtement", hi: "घुटना प्रत्यारोपण लागत: भारत बनाम थाईलैंड बनाम तुर्की, ईमानदारी से", pt: "Custo de prótese de joelho: Índia, Tailândia, Turquia, honestamente", ru: "Стоимость эндопротеза колена: Индия, Таиланд, Турция, честно", tr: "Diz protezi maliyeti: Hindistan, Tayland, Türkiye, dürüstçe" },
    e: { ar: "نفس الزرعة، نفس التقنية، أسعار مختلفة جدًا. لكن السعر الإجمالي هو الفلتر الأول فقط. كيف تختلف الوجهات الثلاث الكبرى فعلًا في فئة الزرعة، حجم حالات الجراح، والعلاج الطبيعي.", bn: "একই ইমপ্লান্ট, একই কৌশল, প্রবলভাবে ভিন্ন মূল্য। কিন্তু শীর্ষ-লাইন খরচ শুধু প্রথম ফিল্টার। তিনটি বড় গন্তব্য কীভাবে ইমপ্লান্ট স্তর, সার্জনের ভলিউম এবং পোস্ট-অপ ফিজিওতে পার্থক্য করে।", fr: "Même implant, même technique, prix très différents. Mais le prix de surface n’est que le premier filtre. Comment les trois grandes destinations diffèrent vraiment sur le tier d’implant, le volume du chirurgien et la rééducation.", hi: "एक ही इम्प्लांट, एक ही तकनीक, बहुत अलग कीमतें। लेकिन शीर्ष लागत केवल पहला फिल्टर है। तीन बड़े गंतव्य इम्प्लांट टीयर, सर्जन वॉल्यूम, और पोस्ट-ऑप फिजियो पर वास्तव में कैसे भिन्न हैं।", pt: "Mesmo implante, mesma técnica, preços muito diferentes. Mas o preço de capa é só o primeiro filtro. Como os três grandes destinos realmente diferem em nível de implante, volume cirúrgico e fisioterapia pós-op.", ru: "Тот же имплант, та же техника, цены очень разные. Но цена-заголовок — только первый фильтр. Как три крупных направления действительно различаются по уровню импланта, объёму хирурга и послеоперационной физиотерапии.", tr: "Aynı implant, aynı teknik, çok farklı fiyatlar. Ancak üst hat maliyet sadece ilk filtre. Üç büyük destinasyonun implant katmanı, cerrah hacmi ve ameliyat sonrası fizyoterapide gerçekten nasıl farklılaştığı." }
  },
  { id: 47,
    t: { ar: "زراعة الشعر في تركيا: ما تفوّته باقة الـ1500$", bn: "তুরস্কে হেয়ার ট্রান্সপ্ল্যান্ট: $১,৫০০ প্যাকেজ যা বাদ দেয়", fr: "Greffe de cheveux en Turquie : ce que le forfait à 1 500 $ omet", hi: "तुर्की में हेयर ट्रांसप्लांट: $1,500 पैकेज क्या छोड़ता है", pt: "Transplante capilar na Turquia: o que o pacote de US$ 1.500 deixa de fora", ru: "Пересадка волос в Турции: что упускает пакет за $1500", tr: "Türkiye'de saç ekimi: 1.500 $ paketi neyi dışarıda bırakır" },
    e: { ar: "نعم، إسطنبول تدير أكبر سوق لزراعة الشعر في العالم، والأسعار رائعة. لكن الباقة الشاملة تخفي عدة بنود مهمة. اقرأ ما نسأل عنه قبل الحجز.", bn: "হ্যাঁ, ইস্তাম্বুল বিশ্বের বৃহত্তম হেয়ার-ট্রান্সপ্ল্যান্ট বাজার চালায়, এবং দাম দুর্দান্ত। কিন্তু অল-ইনক্লুসিভ প্যাকেজ কয়েকটি গুরুত্বপূর্ণ আইটেম লুকায়। বুকিং আগে আমরা যা জিজ্ঞাসা করি।", fr: "Oui, Istanbul gère le plus grand marché mondial de greffes capillaires, et les prix sont remarquables. Mais le forfait tout compris cache plusieurs lignes importantes. Voici ce qu’il faut demander avant de réserver.", hi: "हाँ, इस्तांबुल दुनिया का सबसे बड़ा हेयर-ट्रांसप्लांट बाज़ार चलाता है, और कीमतें उल्लेखनीय हैं। लेकिन ऑल-इनक्लूसिव पैकेज कई महत्वपूर्ण आइटम छुपाता है। बुकिंग से पहले क्या पूछें।", pt: "Sim, Istambul opera o maior mercado mundial de transplante capilar, e os preços são notáveis. Mas o pacote all-inclusive esconde várias linhas importantes. O que perguntar antes de reservar.", ru: "Да, Стамбул держит крупнейший в мире рынок пересадки волос, и цены впечатляют. Но «всё включено» скрывает несколько важных позиций. Что спросить до бронирования.", tr: "Evet, İstanbul dünyanın en büyük saç ekimi pazarını yönetir ve fiyatlar dikkat çekici. Ancak her şey dahil paket önemli birkaç kalemi gizler. Rezervasyon öncesi sormanız gerekenler." }
  },
  { id: 48,
    t: { ar: "معدلات نجاح أطفال الأنابيب: كيف تقرأها (وما لا تنشره العيادات)", bn: "আইভিএফ সাফল্যের হার: কীভাবে পড়বেন (এবং ক্লিনিকগুলি যা প্রকাশ করে না)", fr: "Taux de succès FIV : comment les lire (et ce que les cliniques ne publient pas)", hi: "आईवीएफ सफलता दर: कैसे पढ़ें (और क्लिनिक क्या प्रकाशित नहीं करते)", pt: "Taxas de sucesso da FIV: como ler (e o que as clínicas não publicam)", ru: "Показатели успеха ЭКО: как их читать (и что клиники не публикуют)", tr: "Tüp bebek başarı oranları: nasıl okunur (ve kliniklerin yayınlamadığı şey)" },
    e: { ar: "معدلات نجاح أطفال الأنابيب المنشورة هي أكثر مقياس متلاعب به في السياحة الطبية. كيف تفصل معدل ولادة حقيقيًا عن التسويق، والأسئلة المحددة التي تميّز عيادة جادة عن عدوانية.", bn: "প্রকাশিত আইভিএফ সাফল্যের হার মেডিকেল ট্যুরিজমে সবচেয়ে বেশি কারচুপি করা মেট্রিক। বিপণন থেকে আসল লাইভ-বার্থ রেট কীভাবে আলাদা করবেন এবং কোন নির্দিষ্ট প্রশ্নগুলি গুরুতর ক্লিনিককে আক্রমণাত্মক থেকে আলাদা করে।", fr: "Les taux de succès FIV publiés sont la métrique la plus manipulée du tourisme médical. Comment distinguer un vrai taux de naissance vivante du marketing, et les questions précises qui séparent une clinique sérieuse d’une agressive.", hi: "प्रकाशित आईवीएफ सफलता दरें मेडिकल टूरिज़्म में सबसे अधिक हेरफेर किया गया मीट्रिक हैं। मार्केटिंग से वास्तविक लाइव-बर्थ दर को कैसे अलग करें, और विशिष्ट प्रश्न जो गंभीर क्लिनिक को आक्रामक से अलग करते हैं।", pt: "As taxas publicadas de sucesso de FIV são a métrica mais manipulada no turismo médico. Como separar uma taxa real de nascido vivo do marketing, e as perguntas específicas que separam uma clínica séria de uma agressiva.", ru: "Опубликованные показатели успеха ЭКО — самая искажаемая метрика в медицинском туризме. Как отличить реальную рождаемость от маркетинга, и какие вопросы отделяют серьёзную клинику от агрессивной.", tr: "Yayınlanan tüp bebek başarı oranları tıbbi turizmde en çok manipüle edilen metriktir. Pazarlamadan gerçek canlı doğum oranını nasıl ayırt edileceği ve ciddi bir kliniği agresif olandan ayıran spesifik sorular." }
  },
  { id: 49,
    t: { ar: "متى تحصل على رأي ثانٍ في الأورام في الخارج (ومتى لا)", bn: "বিদেশে দ্বিতীয় অনকোলজি মতামত কখন নেবেন (এবং কখন নয়)", fr: "Quand demander un second avis oncologique à l’étranger (et quand pas)", hi: "विदेश में दूसरी ऑन्कोलॉजी राय कब लें (और कब नहीं)", pt: "Quando buscar segunda opinião oncológica no exterior (e quando não)", ru: "Когда брать второе онкологическое мнение за рубежом (и когда нет)", tr: "Yurt dışında ne zaman ikinci onkoloji görüşü alınmalı (ve ne zaman alınmamalı)" },
    e: { ar: "الرأي الثاني يغيّر التوصية العلاجية في حوالي 28% من حالات الأورام التي نرسلها للخارج. لكن هناك أيضًا حالات لن يساعد فيها. النمط الذي نراه.", bn: "আমরা বিদেশে যে অনকোলজি কেস পাঠাই তার প্রায় ২৮%-এ দ্বিতীয় মতামত চিকিৎসা সুপারিশ পরিবর্তন করে। কিন্তু কিছু কেস আছে যেখানে এটি সাহায্য করবে না। আমরা যে নিদর্শন দেখি।", fr: "Un second avis modifie la recommandation thérapeutique dans environ 28 % des cas oncologiques que nous envoyons à l’étranger. Mais il y a aussi des cas où il n’aidera pas. Le motif que nous voyons.", hi: "दूसरी राय हमारे विदेश भेजे गए लगभग 28% ऑन्कोलॉजी मामलों में उपचार सिफारिश बदल देती है। लेकिन ऐसे मामले भी हैं जहाँ यह मदद नहीं करेगी। हम जो पैटर्न देखते हैं।", pt: "Uma segunda opinião muda a recomendação de tratamento em cerca de 28% dos casos oncológicos que enviamos ao exterior. Mas há casos em que não ajuda. O padrão que vemos.", ru: "Второе мнение меняет рекомендацию по лечению примерно в 28% онкологических случаев, которые мы направляем за рубеж. Но есть случаи, где оно не поможет. Шаблон, который мы видим.", tr: "İkinci görüş, yurt dışına gönderdiğimiz onkoloji vakalarının yaklaşık %28'inde tedavi önerisini değiştirir. Ancak yardımcı olmayacağı vakalar da var. Gördüğümüz örüntü." }
  },
  { id: 50,
    t: { ar: "جراحة السمنة في تركيا: الخمس أسئلة التي تفرز برنامجًا جيدًا من رخيص", bn: "তুরস্কে ব্যারিয়াট্রিক সার্জারি: পাঁচ প্রশ্ন যা ভাল প্রোগ্রামকে সস্তা থেকে আলাদা করে", fr: "Chirurgie bariatrique en Turquie : les cinq questions qui filtrent un bon programme", hi: "तुर्की में बैरिएट्रिक सर्जरी: पाँच प्रश्न जो अच्छे कार्यक्रम को सस्ते से अलग करते हैं", pt: "Cirurgia bariátrica na Turquia: as cinco perguntas que separam um bom programa de um barato", ru: "Бариатрия в Турции: пять вопросов, отделяющих хорошую программу от дешёвой", tr: "Türkiye'de bariatrik cerrahi: iyi bir programı ucuzdan ayıran beş soru" },
    e: { ar: "تركيا تهيمن على السوق الدولي للسمنة من حيث الحجم والسعر. أفضل البرامج عالمية المستوى. الأسوأ يقطع زوايا بطرق لن تشعر بها حتى الشهر السادس. هذه الأسئلة الخمسة تفصل بينهم.", bn: "ভলিউম ও খরচে তুরস্ক আন্তর্জাতিক ব্যারিয়াট্রিক বাজারে প্রভাবশালী। সেরা প্রোগ্রাম সত্যিই বিশ্বমানের। সবচেয়ে খারাপ এমন উপায়ে কর্নার কাটে যা আপনি ছয় মাস পর্যন্ত অনুভব করবেন না। এই পাঁচটি প্রশ্ন তাদের আলাদা করে।", fr: "La Turquie domine le marché bariatrique international en volume et en coût. Les meilleurs programmes sont vraiment de classe mondiale. Les pires coupent des coins de manières qu’on ne ressent qu’au sixième mois. Ces cinq questions les séparent.", hi: "मात्रा और लागत में तुर्की अंतरराष्ट्रीय बैरिएट्रिक बाजार पर हावी है। सर्वश्रेष्ठ कार्यक्रम वास्तव में विश्व स्तरीय हैं। सबसे खराब ऐसे तरीकों से कोनों को काटते हैं जिन्हें आप छठे महीने तक महसूस नहीं करेंगे। ये पाँच प्रश्न उन्हें अलग करते हैं।", pt: "A Turquia domina o mercado bariátrico internacional em volume e custo. Os melhores programas são genuinamente de classe mundial. Os piores cortam custos de formas que você não sente até o sexto mês. Essas cinco perguntas os separam.", ru: "Турция доминирует на международном бариатрическом рынке по объёму и стоимости. Лучшие программы действительно мирового класса. Худшие срезают углы так, что вы это почувствуете только к шестому месяцу. Эти пять вопросов их разделяют.", tr: "Türkiye uluslararası bariatrik pazarda hacim ve maliyet açısından baskın. En iyi programlar gerçekten dünya çapında. En kötüler altıncı aya kadar hissetmeyeceğiniz şekillerde köşe kesiyor. Bu beş soru onları ayırıyor." }
  },
  { id: 51,
    t: { ar: "ألمانيا مقابل الهند للجراحة المعقدة: متى يستحق فارق السعر", bn: "জটিল সার্জারির জন্য জার্মানি বনাম ভারত: কখন মূল্য ব্যবধান পরিশোধের যোগ্য", fr: "Allemagne ou Inde pour chirurgie complexe : quand l’écart de prix vaut la peine", hi: "जटिल सर्जरी के लिए जर्मनी बनाम भारत: कब मूल्य अंतर भुगतान योग्य है", pt: "Alemanha vs Índia para cirurgia complexa: quando o gap de preço vale a pena", ru: "Германия vs Индия для сложной хирургии: когда разница в цене оправдана", tr: "Karmaşık cerrahi için Almanya vs Hindistan: fiyat farkı ne zaman ödemeye değer" },
    e: { ar: "ألمانيا عادةً 5-8× تكلفة الهند للجراحة المعقدة. أحيانًا هذا هو القرار الصحيح. في الغالب ليس كذلك. النمط الذي رأيناه عبر 400+ إحالة معقدة.", bn: "জটিল সার্জারির জন্য জার্মানি সাধারণত ভারতের ৫-৮× খরচ। কখনো এটি সঠিক সিদ্ধান্ত। বেশিরভাগ সময় না। ৪০০+ জটিল রেফারেলে আমরা যে নিদর্শন দেখেছি।", fr: "L’Allemagne coûte typiquement 5 à 8× plus que l’Inde pour la chirurgie complexe. Parfois c’est le bon choix. Plus souvent non. Le motif vu sur 400+ référencements complexes.", hi: "जटिल सर्जरी के लिए जर्मनी आमतौर पर भारत की 5-8× लागत। कभी यह सही निर्णय। अक्सर नहीं। 400+ जटिल रेफरल में हमने देखा पैटर्न।", pt: "Alemanha custa tipicamente 5-8× mais que a Índia para cirurgia complexa. Às vezes é a escolha certa. Mais frequentemente não é. O padrão visto em 400+ encaminhamentos complexos.", ru: "Германия обычно в 5-8 раз дороже Индии для сложной хирургии. Иногда это правильный выбор. Чаще нет. Шаблон, который мы видели по 400+ сложным направлениям.", tr: "Almanya karmaşık cerrahide Hindistan'ın tipik olarak 5-8 katıdır. Bazen doğru karar. Çoğu zaman değil. 400+ karmaşık sevkte gördüğümüz örüntü." }
  },
  { id: 52,
    t: { ar: "تعافي CABG: ما يحدث فعلًا في الأسابيع الـ12 الأولى", bn: "CABG পুনরুদ্ধার: প্রথম ১২ সপ্তাহে আসলে কী হয়", fr: "Récupération CABG : ce qui se passe vraiment lors des 12 premières semaines", hi: "CABG रिकवरी: पहले 12 हफ्तों में वास्तव में क्या होता है", pt: "Recuperação CABG: o que realmente acontece nas primeiras 12 semanas", ru: "Восстановление после АКШ: что реально происходит в первые 12 недель", tr: "CABG iyileşmesi: ilk 12 haftada gerçekten ne olur" },
    e: { ar: "معظم جداول تعافي CABG على الإنترنت مثالية. هنا أسبوع بأسبوع واقعي من 180+ مريض CABG دولي وجّهناه في العامين الماضيين.", bn: "ইন্টারনেটে বেশিরভাগ CABG পুনরুদ্ধার টাইমলাইন আকাঙ্ক্ষামূলক। গত দুই বছরে আমরা যে ১৮০+ আন্তর্জাতিক CABG রোগীকে রুট করেছি তাদের থেকে বাস্তবিক সপ্তাহ-প্রতি-সপ্তাহ।", fr: "La plupart des chronologies de récupération CABG sur Internet sont idéalistes. Voici un déroulé semaine par semaine réaliste tiré des 180+ patients internationaux que nous avons dirigés ces deux dernières années.", hi: "इंटरनेट पर अधिकांश CABG रिकवरी टाइमलाइन आकांक्षात्मक हैं। पिछले दो वर्षों में हमने जिन 180+ अंतरराष्ट्रीय CABG मरीज़ों को रूट किया उनसे यथार्थवादी सप्ताह-दर-सप्ताह।", pt: "A maioria dos cronogramas de recuperação CABG na internet é aspiracional. Aqui um semana-a-semana realista dos 180+ pacientes CABG internacionais que roteamos nos últimos dois anos.", ru: "Большинство графиков восстановления после АКШ в интернете идеализированные. Вот реалистичная неделя за неделей от более чем 180 международных пациентов АКШ, которых мы маршрутизировали за последние два года.", tr: "İnternetteki çoğu CABG iyileşme zaman çizelgesi aspirasyoneldir. İşte son iki yılda yönlendirdiğimiz 180+ uluslararası CABG hastasından gerçekçi hafta hafta." }
  },
  { id: 53,
    t: { ar: "العلاج بالبروتون في الخارج: متى يستحق الانعطاف (ومتى لا)", bn: "বিদেশে প্রোটন থেরাপি: কখন এটি ভ্রমণের যোগ্য (এবং কখন না)", fr: "Protonthérapie à l’étranger : quand le détour vaut le coup (et quand non)", hi: "विदेश में प्रोटॉन थेरेपी: कब डिटूर के लायक (और कब नहीं)", pt: "Terapia com prótons no exterior: quando vale o desvio (e quando não)", ru: "Протонная терапия за рубежом: когда стоит ехать (а когда нет)", tr: "Yurt dışı proton tedavisi: ne zaman değer (ve ne zaman değmez)" },
    e: { ar: "حزمة البروتون مُبالغ في تسويقها. لحالات الأطفال وأورام بالغين محددة تتفوق فعلًا على الإشعاع الفوتوني؛ لمعظم حالات البروستاتا والثدي لا تتفوق. قراءتنا.", bn: "প্রোটন বিম অতিবিক্রিত। পেডিয়াট্রিক কেস এবং নির্দিষ্ট প্রাপ্তবয়স্ক টিউমারের জন্য এটি ফোটন রেডিয়েশনকে সত্যিই ছাড়িয়ে যায়; বেশিরভাগ প্রোস্টেট ও স্তন কেসে নয়। আমাদের পঠন।", fr: "La protonthérapie est sur-vendue. Pour les cas pédiatriques et certaines tumeurs adultes, elle surpasse vraiment la photonthérapie ; pour la plupart des prostates et des seins, non. Notre lecture.", hi: "प्रोटॉन बीम अधिक बेचा जाता है। बाल मामलों और विशिष्ट वयस्क ट्यूमर के लिए यह वास्तव में फोटॉन विकिरण से बेहतर प्रदर्शन करता है; अधिकांश प्रोस्टेट और स्तन मामलों में नहीं। हमारा पठन।", pt: "Feixe de prótons é supervalorizado. Para casos pediátricos e tumores adultos específicos, supera genuinamente a radiação de fótons; para a maioria dos casos de próstata e mama, não. Nossa leitura.", ru: "Протонный пучок переоценён. Для педиатрии и определённых взрослых опухолей он действительно превосходит фотонное облучение; для большинства случаев простаты и груди — нет. Наш взгляд.", tr: "Proton ışını fazla satılıyor. Pediatrik vakalar ve belirli yetişkin tümörleri için foton radyasyonundan gerçekten üstündür; çoğu prostat ve meme vakası için değil. Bizim okumamız." }
  },
  { id: 54,
    t: { ar: "DBS لمرض باركنسون: الأسئلة الخمس التي تفرز مركزًا جيدًا", bn: "পার্কিনসনের জন্য DBS: ভাল কেন্দ্র ফিল্টার করার পাঁচটি প্রশ্ন", fr: "DBS pour Parkinson : les cinq questions qui filtrent un bon centre", hi: "पार्किंसन के लिए DBS: एक अच्छे केंद्र को फ़िल्टर करने वाले पाँच प्रश्न", pt: "DBS para Parkinson: as cinco perguntas que filtram um bom centro", ru: "DBS при болезни Паркинсона: пять вопросов, отсеивающих хороший центр", tr: "Parkinson için DBS: iyi bir merkezi filtreleyen beş soru" },
    e: { ar: "التحفيز العميق للدماغ تحوّلي للمرشح المناسب وكارثي للمرشح الخاطئ. كيف نفحص المراكز والحالات قبل إرسال المرضى للخارج.", bn: "ডিপ ব্রেইন স্টিমুলেশন সঠিক প্রার্থীর জন্য রূপান্তরমূলক এবং ভুল প্রার্থীর জন্য বিপর্যয়। বিদেশে রোগী পাঠানোর আগে আমরা কীভাবে কেন্দ্র ও কেস স্ক্রিন করি।", fr: "La stimulation cérébrale profonde transforme la vie du bon candidat et est désastreuse pour le mauvais. Comment nous filtrons centres et cas avant d’envoyer des patients à l’étranger.", hi: "डीप ब्रेन स्टिमुलेशन सही उम्मीदवार के लिए परिवर्तनकारी और गलत के लिए विनाशकारी है। हम विदेश में मरीज़ भेजने से पहले केंद्रों और मामलों की जाँच कैसे करते हैं।", pt: "A estimulação cerebral profunda é transformadora para o candidato certo e desastrosa para o errado. Como filtramos centros e casos antes de enviar pacientes ao exterior.", ru: "Глубокая стимуляция мозга преображает подходящего кандидата и катастрофична для неподходящего. Как мы отбираем центры и случаи перед отправкой пациентов за рубеж.", tr: "Derin beyin stimülasyonu doğru aday için dönüştürücü, yanlış aday için felakettir. Hastaları yurt dışına göndermeden önce merkezleri ve vakaları nasıl tarıyoruz." }
  },
  { id: 55,
    t: { ar: "جراحة القلب الخلقية للأطفال في الخارج: قائمة فريق مخصص", bn: "বিদেশে পেডিয়াট্রিক কার্ডিয়াক সার্জারি: ডেডিকেটেড-টিম চেকলিস্ট", fr: "Chirurgie cardiaque pédiatrique à l’étranger : la checklist équipe dédiée", hi: "विदेश में पेडियाट्रिक कार्डिएक सर्जरी: समर्पित-टीम चेकलिस्ट", pt: "Cirurgia cardíaca pediátrica no exterior: checklist da equipe dedicada", ru: "Детская кардиохирургия за рубежом: чек-лист выделенной команды", tr: "Yurt dışı pediatrik kalp cerrahisi: özel ekip kontrol listesi" },
    e: { ar: "\"صديق للأطفال\" تسويق. برنامج قلب أطفال مخصص سريري. كيف تميّز بينهما عند اختيار مستشفى لطفلك.", bn: "\"পেডিয়াট্রিক-ফ্রেন্ডলি\" বিপণন। একটি ডেডিকেটেড পেডিয়াট্রিক কার্ডিয়াক প্রোগ্রাম ক্লিনিক্যাল। আপনার সন্তানের জন্য হাসপাতাল নির্বাচন করার সময় তাদের কীভাবে আলাদা করবেন।", fr: "« Adapté aux enfants » est du marketing. Un programme cardiaque pédiatrique dédié est clinique. Comment les distinguer en choisissant un hôpital pour votre enfant.", hi: "\"पेडियाट्रिक-फ्रेंडली\" मार्केटिंग है। एक समर्पित पेडियाट्रिक कार्डिएक प्रोग्राम क्लिनिकल है। अपने बच्चे के लिए अस्पताल चुनते समय उन्हें कैसे अलग करें।", pt: "\"Pediátrico-amigável\" é marketing. Um programa cardíaco pediátrico dedicado é clínico. Como diferenciá-los ao escolher um hospital para seu filho.", ru: "«Дружелюбный к детям» — это маркетинг. Выделенная детская кардиологическая программа — это клиника. Как отличить их, выбирая больницу для ребёнка.", tr: "\"Pediatrik dostu\" pazarlamadır. Adanmış pediatrik kalp programı kliniktir. Çocuğunuz için hastane seçerken onları nasıl ayırt edersiniz." }
  },
  { id: 56,
    t: { ar: "زراعة الكلى من متبرع حي في الخارج: التحضيرات قبل السفر التي لا يتحدث عنها أحد", bn: "বিদেশে জীবিত-দাতা কিডনি ট্রান্সপ্ল্যান্ট: কেউ কথা না বলা প্রি-ট্রাভেল ওয়ার্কআপ", fr: "Greffe de rein de donneur vivant à l’étranger : le bilan pré-voyage dont personne ne parle", hi: "विदेश में जीवित-दाता गुर्दा प्रत्यारोपण: प्री-ट्रैवल वर्कअप जिसके बारे में कोई बात नहीं करता", pt: "Transplante de rim de doador vivo no exterior: o workup pré-viagem que ninguém menciona", ru: "Трансплантация почки от живого донора за рубежом: подготовка до поездки, о которой никто не говорит", tr: "Yurt dışı canlı-donör böbrek nakli: kimsenin konuşmadığı seyahat öncesi hazırlık" },
    e: { ar: "الجميع يركّز على الجراحة. الـ3-4 أشهر من التحضيرات قبل السفر هي حيث تنجح الزراعة فعلًا أو تفشل. التسلسل.", bn: "সবাই সার্জারিতে ফোকাস করে। প্রি-ট্রাভেল ওয়ার্কআপের ৩-৪ মাসই হল যেখানে ট্রান্সপ্ল্যান্ট আসলে সফল বা ব্যর্থ হয়। ক্রমাবলি।", fr: "Tout le monde se focalise sur l’opération. Les 3 à 4 mois de bilan pré-voyage sont là où les greffes réussissent ou échouent vraiment. La séquence.", hi: "हर कोई सर्जरी पर ध्यान केंद्रित करता है। प्री-ट्रैवल वर्कअप के 3-4 महीने वहाँ हैं जहाँ प्रत्यारोपण वास्तव में सफल या असफल होते हैं। अनुक्रम।", pt: "Todos focam na cirurgia. Os 3-4 meses de workup pré-viagem são onde transplantes realmente têm sucesso ou falham. A sequência.", ru: "Все фокусируются на операции. 3-4 месяца подготовки до поездки — это где трансплантации реально удаются или проваливаются. Последовательность.", tr: "Herkes ameliyata odaklanır. Seyahat öncesi 3-4 aylık hazırlık, naklin gerçekten başarılı olduğu veya başarısız olduğu yerdir. Sıralama." }
  },
  { id: 57,
    t: { ar: "الدفع للسفر الطبي: الضمان، الصرف، وسؤال الاسترداد", bn: "মেডিকেল ভ্রমণের জন্য পেমেন্ট: এসক্রো, FX, এবং রিফান্ড প্রশ্ন", fr: "Payer un voyage médical : escrow, change et question de remboursement", hi: "चिकित्सा यात्रा के लिए भुगतान: एस्क्रो, FX, और रिफंड प्रश्न", pt: "Pagando por viagem médica: escrow, FX e a questão do reembolso", ru: "Оплата медицинской поездки: эскроу, валюта и вопрос возврата", tr: "Tıbbi seyahat için ödeme: emanet, döviz ve geri ödeme sorusu" },
    e: { ar: "دفع لمستشفى لم تلتقِه أبدًا، بعملة ليست لك، لجراحة لم تخضع لها بعد، أغرب مما يبدو. مكدس الدفع الذي يحميك فعلًا.", bn: "এমন একটি হাসপাতালকে অর্থ প্রদান করা যা আপনি কখনো দেখেননি, এমন মুদ্রায় যা আপনার নয়, এমন সার্জারির জন্য যা আপনি এখনো করেননি — এটি যা শোনা যায় তার চেয়ে অদ্ভুত। যে পেমেন্ট স্ট্যাক আসলে আপনাকে রক্ষা করে।", fr: "Payer un hôpital que vous n’avez jamais rencontré, dans une devise qui n’est pas la vôtre, pour une opération que vous n’avez pas encore subie est plus étrange qu’il n’y paraît. Le stack de paiement qui vous protège vraiment.", hi: "एक अस्पताल को भुगतान करना जिसे आप कभी नहीं मिले, ऐसी मुद्रा में जो आपकी नहीं है, ऐसी सर्जरी के लिए जो आपने अभी तक नहीं की है — जितना लगता है उससे अजीब है। वह भुगतान स्टैक जो वास्तव में आपकी रक्षा करता है।", pt: "Pagar um hospital que você nunca conheceu, em moeda que não é sua, por cirurgia que ainda não fez é mais estranho que parece. O stack de pagamento que realmente te protege.", ru: "Платить больнице, которую вы никогда не видели, в валюте, которая не ваша, за операцию, которую вы ещё не сделали, страннее, чем звучит. Платёжный стек, который реально вас защищает.", tr: "Hiç tanışmadığınız bir hastaneye, sizin olmayan bir para biriminde, henüz yapmadığınız bir ameliyat için ödeme yapmak göründüğünden daha tuhaftır. Sizi gerçekten koruyan ödeme katmanı." }
  },
  { id: 58,
    t: { ar: "تأمين السفر الطبي: ما يغطّيه فعلًا (وما لا يغطّيه)", bn: "মেডিকেল ভ্রমণ বীমা: যা আসলে আপনাকে কভার করে (এবং যা করে না)", fr: "Assurance voyage médical : ce qui vous couvre vraiment (et ce qui ne couvre pas)", hi: "चिकित्सा यात्रा बीमा: जो वास्तव में आपको कवर करता है (और जो नहीं करता)", pt: "Seguro para viagem médica: o que realmente cobre (e o que não cobre)", ru: "Страховка для медицинской поездки: что действительно покрывает (а что нет)", tr: "Tıbbi seyahat sigortası: gerçekten neyi kapsıyor (ve neyi kapsamıyor)" },
    e: { ar: "تأمين السفر العادي يستثني الرعاية الطبية المخططة صراحةً. حفنة من المنتجات المتخصصة تغطي مخاطر السفر الطبي فعلًا. الخريطة.", bn: "নিয়মিত ভ্রমণ বীমা পরিকল্পিত চিকিৎসা যত্নকে স্পষ্টভাবে বাদ দেয়। মুষ্টিমেয় বিশেষায়িত পণ্য আসলে মেডিকেল-ভ্রমণ ঝুঁকি কভার করে। মানচিত্র।", fr: "L’assurance voyage classique exclut explicitement les soins médicaux planifiés. Quelques produits spécialisés couvrent vraiment les risques de voyage médical. La carte.", hi: "नियमित यात्रा बीमा स्पष्ट रूप से नियोजित चिकित्सा देखभाल को बाहर करता है। कुछ विशिष्ट उत्पाद वास्तव में चिकित्सा-यात्रा जोखिमों को कवर करते हैं। मानचित्र।", pt: "Seguro de viagem regular exclui explicitamente cuidado médico planejado. Alguns produtos especializados cobrem riscos de viagem médica. O mapa.", ru: "Обычная туристическая страховка прямо исключает плановое медицинское лечение. Несколько специализированных продуктов действительно покрывают риски медицинской поездки. Карта.", tr: "Normal seyahat sigortası planlı tıbbi bakımı açıkça hariç tutar. Birkaç uzmanlaşmış ürün gerçekten tıbbi seyahat risklerini kapsar. Harita." }
  },
  { id: 59,
    t: { ar: "العلاج بالخلايا الجذعية: فصل 15% بدليل حقيقي عن 85% تسويقًا", bn: "স্টেম-সেল থেরাপি: প্রকৃত প্রমাণ সহ ১৫% থেকে বিপণন এমন ৮৫% পৃথক করা", fr: "Thérapie cellulaire souche : séparer les 15 % avec preuves réelles des 85 % de marketing", hi: "स्टेम-सेल थेरेपी: 15% जो वास्तविक साक्ष्य के साथ है उन्हें 85% मार्केटिंग से अलग करना", pt: "Terapia com células-tronco: separar os 15% com evidência real dos 85% de marketing", ru: "Стволовая клеточная терапия: отделить 15% с реальными доказательствами от 85% маркетинга", tr: "Kök hücre tedavisi: gerçek kanıta sahip %15'i pazarlama olan %85'ten ayırmak" },
    e: { ar: "سياحة الخلايا الجذعية من أكثر فئات الطب ضجيجًا على الإنترنت. لحفنة من الحالات هناك دليل حقيقي؛ لمعظمها لا يوجد. كيف نصنّف.", bn: "স্টেম-সেল ট্যুরিজম ইন্টারনেটে সবচেয়ে হাইপ-ভারী চিকিৎসা শ্রেণীগুলির একটি। মুষ্টিমেয় কেসের জন্য প্রকৃত প্রমাণ আছে; বেশিরভাগের জন্য নেই। আমরা কীভাবে ট্রাইজ করি।", fr: "Le tourisme des cellules souches est l’une des catégories médicales les plus survendues sur Internet. Pour quelques pathologies il existe des preuves réelles ; pour la plupart, non. Comment nous trions.", hi: "स्टेम-सेल टूरिज़्म इंटरनेट पर सबसे अधिक हाइप वाली चिकित्सा श्रेणियों में से एक है। मुट्ठी भर स्थितियों के लिए वास्तविक साक्ष्य हैं; अधिकांश के लिए नहीं। हम कैसे ट्राइएज करते हैं।", pt: "Turismo de células-tronco é uma das categorias médicas mais cheias de hype na internet. Para algumas condições há evidência real; para a maioria, não. Como triamos.", ru: "Туризм стволовых клеток — одна из самых раздутых медицинских категорий в интернете. Для нескольких состояний есть реальные доказательства; для большинства — нет. Как мы сортируем.", tr: "Kök hücre turizmi internetteki en abartılı tıbbi kategorilerden biridir. Birkaç durum için gerçek kanıt var; çoğu için yok. Nasıl triyajlıyoruz." }
  },
  { id: 60,
    t: { ar: "زراعة القرنية في الخارج: ما يدفع وقت الانتظار (وكيف تختصره)", bn: "বিদেশে কর্নিয়া ট্রান্সপ্ল্যান্ট: অপেক্ষার সময়কে কী চালিত করে (এবং এটি কীভাবে ছোট করবেন)", fr: "Greffe de cornée à l’étranger : ce qui dicte le temps d’attente (et comment le réduire)", hi: "विदेश में कॉर्निया प्रत्यारोपण: प्रतीक्षा समय को क्या चलाता है (और इसे कैसे छोटा करें)", pt: "Transplante de córnea no exterior: o que determina o tempo de espera (e como reduzi-lo)", ru: "Трансплантация роговицы за рубежом: что определяет время ожидания (и как его сократить)", tr: "Yurt dışında kornea nakli: bekleme süresini ne belirler (ve nasıl kısaltılır)" },
    e: { ar: "أوقات انتظار زراعة القرنية تتباين بشكل كبير بين الدول. بعض التباين حقيقي؛ بعضه يتعلق بمن لديه بنك عيون عامل ومن لا.", bn: "কর্নিয়া ট্রান্সপ্ল্যান্ট অপেক্ষার সময় দেশভেদে ব্যাপকভাবে পরিবর্তিত হয়। কিছু পার্থক্য আসল; কিছু কে কার্যকর আই ব্যাঙ্ক আছে এবং কে নেই তার সম্পর্কে।", fr: "Les délais de greffe de cornée varient énormément entre pays. Une partie est réelle ; une partie tient à qui dispose d’une banque oculaire fonctionnelle.", hi: "कॉर्निया ट्रांसप्लांट के इंतज़ार के समय देशों के बीच बेहद भिन्न होते हैं। कुछ अंतर वास्तविक है; कुछ इस बारे में है कि किसके पास कार्यात्मक आई बैंक है और किसके पास नहीं।", pt: "Tempos de espera para transplante de córnea variam enormemente entre países. Parte da variação é real; parte é sobre quem tem banco de olhos funcional e quem não tem.", ru: "Время ожидания трансплантации роговицы сильно различается между странами. Часть разницы реальна; часть зависит от того, у кого есть работающий глазной банк, а у кого нет.", tr: "Kornea nakli bekleme süreleri ülkeler arasında büyük farklılık gösterir. Varyansın bir kısmı gerçektir; bir kısmı kimin işleyen bir göz bankasına sahip olduğu ve olmadığı ile ilgilidir." }
  },
  { id: 61,
    t: { ar: "سرطان البروستاتا: الجراحة الروبوتية مقابل المفتوحة مقابل الإشعاع (ولماذا 'أحدث تقنية' ليست الجواب)", bn: "প্রোস্টেট ক্যান্সার: রোবোটিক বনাম ওপেন বনাম রেডিয়েশন (এবং কেন 'সর্বশেষ প্রযুক্তি' উত্তর নয়)", fr: "Cancer de la prostate : chirurgie robotique vs ouverte vs radiothérapie (et pourquoi « technologie la plus récente » n’est pas la réponse)", hi: "प्रोस्टेट कैंसर: रोबोटिक बनाम ओपन बनाम विकिरण (और क्यों 'नवीनतम तकनीक' उत्तर नहीं)", pt: "Câncer de próstata: cirurgia robótica vs aberta vs radiação (e por que 'tecnologia mais recente' não é a resposta)", ru: "Рак простаты: роботическая vs открытая хирургия vs облучение (и почему «новейшая технология» не ответ)", tr: "Prostat kanseri: robotik vs açık cerrahi vs radyasyon (ve 'en son teknoloji'nin neden yanıt olmadığı)" },
    e: { ar: "علاج سرطان البروستاتا حيث يتباعد التسويق الضوضائي والنتائج الحقيقية بأقصى قدر. كيف نؤطّر القرار للمرضى الدوليين الذين نوجّههم.", bn: "প্রোস্টেট ক্যান্সার চিকিৎসা যেখানে বিপণন হাইপ এবং প্রকৃত ফলাফল সবচেয়ে বেশি বিচ্যুত হয়। আমরা যে আন্তর্জাতিক রোগীদের রুট করি তাদের জন্য আমরা সিদ্ধান্ত কীভাবে গঠন করি।", fr: "Le traitement du cancer de la prostate est l’endroit où le hype marketing et les vrais résultats divergent le plus. Comment nous cadrons la décision pour les patients internationaux que nous orientons.", hi: "प्रोस्टेट कैंसर उपचार वह जगह है जहाँ मार्केटिंग हाइप और वास्तविक परिणाम सबसे अधिक भिन्न होते हैं। हम जिन अंतरराष्ट्रीय मरीज़ों को रूट करते हैं उनके लिए हम निर्णय कैसे फ्रेम करते हैं।", pt: "Tratamento de câncer de próstata é onde o hype de marketing e resultados reais divergem mais. Como enquadramos a decisão para os pacientes internacionais que roteamos.", ru: "Лечение рака простаты — там, где маркетинговый шум и реальные результаты расходятся сильнее всего. Как мы структурируем решение для иностранных пациентов, которых маршрутизируем.", tr: "Prostat kanseri tedavisi pazarlama abartısı ve gerçek sonuçların en çok ayrıştığı yerdir. Yönlendirdiğimiz uluslararası hastalar için kararı nasıl çerçeveliyoruz." }
  },
];

async function main() {
  let inserted = 0, updated = 0;
  for (const p of POSTS) {
    for (const locale of LOCALES) {
      for (const [field, value] of [["title", p.t[locale]], ["excerpt", p.e[locale]]] as const) {
        const result = await db.execute(sql`
          INSERT INTO translations (translatable_type, translatable_id, locale, field_name, value,
                                    is_machine_translated, is_reviewed, reviewed_by, reviewed_at)
          VALUES ('blog_post', ${p.id}, ${locale}, ${field}, ${value}, false, true, 'manual-wave2.20b', NOW())
          ON CONFLICT (translatable_type, translatable_id, locale, field_name)
          DO UPDATE SET value = EXCLUDED.value, is_machine_translated = false, is_reviewed = true,
                        reviewed_by = 'manual-wave2.20b', reviewed_at = NOW(), updated_at = NOW()
          RETURNING (xmax = 0) AS inserted
        `);
        const row = Array.from(result as any)[0] as any;
        if (row?.inserted) inserted++; else updated++;
      }
    }
  }
  console.log(`Wave 2.20b complete: inserted=${inserted} updated=${updated}`);
  console.log(`Total: ${inserted + updated} (${POSTS.length} posts × ${LOCALES.length} locales × 2 fields)`);
  process.exit(0);
}
main().catch((e) => { console.error(e); process.exit(1); });
