/**
 * Deep hospital image scraper.
 *
 * Phase 21's scraper only checked og:image / twitter:image / image_src meta tags.
 * Many hospital websites omit those but still embed real building/interior photos
 * in the homepage HTML. This goes deeper:
 *   1. Fetch homepage (and try /about, /home, /gallery, /facilities on miss)
 *   2. Extract every <img src=...> URL from HTML (regex, no DOM)
 *   3. Filter out logos, icons, spacers, ads, social-media buttons
 *   4. Score remaining images by likely-hero signals (banner / hero / building
 *      keyword in URL/path; explicit width or height ≥ 600 in attrs; aspect-
 *      ratio hint via filename)
 *   5. Pick the best candidate, validate it's reachable + ≥ 30KB, write to DB
 *
 * Skips hospitals that already have a non-Unsplash cover (real photos preserved).
 * Targets hospitals where current cover is an Unsplash fallback OR is NULL.
 *
 * Run:
 *   node --env-file=.env.local --import tsx scripts/import/scrape-hospital-images-deep.ts
 *   ... --limit=500
 *   ... --country=india
 *   ... --concurrency=12
 */
import postgres from "postgres";

const LIMIT = Number(process.argv.find((a) => a.startsWith("--limit="))?.slice(8) ?? 4000);
const ONLY_COUNTRY = process.argv.find((a) => a.startsWith("--country="))?.slice(10);
const CONCURRENCY = Number(process.argv.find((a) => a.startsWith("--concurrency="))?.slice(14) ?? 10);
const REQUEST_TIMEOUT_MS = 8000;

const UA = "Mozilla/5.0 (compatible; MedCastsBot/1.0; +https://medcasts.com/bot)";

type Row = { id: number; slug: string; website: string };

// Blocklist applied to URL path. Anchored so `logoem.jpg` is caught while
// `cardiology-program.jpg` is not.
const SKIP_PATTERNS = [
  // Logos in any form
  /logo[a-z0-9]*\.(jpe?g|png|webp|gif|svg)/i,
  /(^|[\/_-])logos?([\/_.\-]|$)/i,
  // Icons / decorative
  /(^|[\/_-])icons?([\/_.\-]|$)/i,
  /icon[a-z0-9]*\.(jpe?g|png|webp|gif|svg)/i,
  /(^|[\/_-])spacer/i,
  /(^|[\/_-])blank/i,
  /(^|[\/_-])placeholder/i,
  /(^|[\/_-])pixel/i,
  /(^|[\/_-])button/i,
  /(^|[\/_-])social/i,
  /facebook|twitter|instagram|youtube|linkedin|whatsapp|tiktok|pinterest|telegram/i,
  /(^|[\/_-])avatar/i,
  /favicon/i,
  /apple-touch/i,
  /\.(svg|gif|ico)(\?|$)/i,
  /(^|[\/_-])signature/i,
  /(^|[\/_-])arrow/i,
  /(^|[\/_-])bullet/i,
  /(^|[\/_-])divider/i,
  /(^|[\/_-])bg[\/_-]/i,
  /tracking/i,
  /pixel\.gif/i,
  /(^|[\/_-])share[\/_-]/i,
  /(^|[\/_-])loading/i,
  /(^|[\/_-])loader/i,
  /(^|[\/_-])sprite/i,
  /(^|[\/_-])brand[\/_-]/i,
  /(^|[\/_-])header[\/_-]/i,
  /(^|[\/_-])footer[\/_-]/i,
  /banner[\/_-]?(strip|cta|notice|alert|popup)/i,
  // Patient / doctor portraits, staff photos — hospital page should show building/interior, not people
  /(^|[\/_-])doctor[a-z0-9_-]*\.(jpe?g|png|webp|gif)/i,
  /(^|[\/_-])dr[\/_-][a-z0-9_-]*\.(jpe?g|png|webp|gif)/i,
  /(^|[\/_-])staff/i,
  /(^|[\/_-])team[\/_-]/i,
  /(^|[\/_-])patient[\/_-]/i,
  /(^|[\/_-])testimonial/i,
  // Documents / notices / announcements / circulars — usually scanned PDFs as images
  /(^|[\/_-])(notice|circular|announcement|tender|advert|ad|notification)/i,
  /(^|[\/_-])(donation|donate|donor)/i,
  /(^|[\/_-])(award|certificate|trophy|recognition|accreditation)/i,
  /(^|[\/_-])(payment|invoice|receipt|bill)/i,
  /(^|[\/_-])(faq|contact|career|job|vacancy|apply)/i,
  // Generic / autogenerated names → low signal
  /(^|[\/_-])(class|grade|news[\/_-]?|article|blog[\/_-]?)/i,
  /MicrosoftTeams-image/i,
  /Untitled[\/_-]?design/i,
  /(^|[\/_-])screenshot/i,
  /(^|[\/_-])screen[\/_-]?shot/i,
  /(^|[\/_-])capture/i,
  // App store / play store badges
  /(google[\/_-]?play|app[\/_-]?store|play[\/_-]?store)/i,
];

// Boost score if URL/path contains one of these (likely hero / building photo)
const POSITIVE_KEYWORDS = [
  /\bhospital\b/i,
  /\bbuilding\b/i,
  /\bbanner\b/i,
  /\bhero\b/i,
  /\bslide(r|show)?\b/i,
  /\bcover\b/i,
  /\bmain\b/i,
  /\bentrance\b/i,
  /\bexterior\b/i,
  /\binterior\b/i,
  /\bward\b/i,
  /\bicu\b/i,
  /\boperat(ing|ion)\b/i,
  /\bfacility\b/i,
  /\bfacilities\b/i,
  /\binfra(structure)?\b/i,
  /\bcampus\b/i,
  /\bclinic\b/i,
  /\babout\b/i,
  /\bhome[-_]/i,
];

const FALLBACK_PATHS = ["/about", "/about-us", "/gallery", "/facilities", "/infrastructure"];

function shouldSkip(url: string, alt = ""): boolean {
  const haystack = `${url} ${alt}`;
  return SKIP_PATTERNS.some((re) => re.test(haystack));
}

function scoreImage(url: string, width?: number, height?: number, alt = ""): number {
  let score = 0;
  const haystack = `${url} ${alt}`.toLowerCase();
  for (const re of POSITIVE_KEYWORDS) if (re.test(haystack)) score += 5;
  // Big explicit dimensions
  if (width && width >= 600) score += 3;
  if (height && height >= 400) score += 2;
  if (width && width >= 1000) score += 4;
  // Penalize square small images (likely thumbnails)
  if (width && height && width < 300 && height < 300) score -= 5;
  // jpg + jpeg are more likely real photos than webp icons
  if (/\.(jpe?g|webp)(\?|$)/i.test(url)) score += 1;
  // Folder hints
  if (/\/upload(s)?\//i.test(url)) score += 2;
  if (/\/wp-content\/uploads\//i.test(url)) score += 2;
  if (/\/(media|assets|images|photos|gallery)\//i.test(url)) score += 1;
  return score;
}

function resolveUrl(raw: string, base: string): string | null {
  try {
    if (/^https?:\/\//i.test(raw)) return raw;
    if (raw.startsWith("//")) return "https:" + raw;
    if (raw.startsWith("data:")) return null;
    return new URL(raw, base).toString();
  } catch {
    return null;
  }
}

// Parse <img> tags + extract src + width/height/alt attributes.
function extractImages(html: string, baseUrl: string): Array<{ url: string; w?: number; h?: number; alt: string }> {
  const out: Array<{ url: string; w?: number; h?: number; alt: string }> = [];
  const imgRe = /<img\b([^>]*)>/gi;
  let m: RegExpExecArray | null;
  while ((m = imgRe.exec(html)) !== null) {
    const attrs = m[1];
    const srcMatch = attrs.match(/\b(?:data-src|data-original|src)\s*=\s*["']([^"']+)["']/i);
    if (!srcMatch) continue;
    const raw = srcMatch[1].trim();
    const abs = resolveUrl(raw, baseUrl);
    if (!abs || !/^https?:\/\//i.test(abs)) continue;
    const widthMatch = attrs.match(/\bwidth\s*=\s*["']?(\d+)["']?/i);
    const heightMatch = attrs.match(/\bheight\s*=\s*["']?(\d+)["']?/i);
    const altMatch = attrs.match(/\balt\s*=\s*["']([^"']*)["']/i);
    out.push({
      url: abs,
      w: widthMatch ? Number(widthMatch[1]) : undefined,
      h: heightMatch ? Number(heightMatch[1]) : undefined,
      alt: altMatch ? altMatch[1] : "",
    });
  }
  return out;
}

// Also pick up CSS background-image: url(...) tokens — many hospital sites
// put their hero photo on a div as a background.
function extractBackgrounds(html: string, baseUrl: string): Array<{ url: string; alt: string }> {
  const out: Array<{ url: string; alt: string }> = [];
  const re = /background(?:-image)?\s*:\s*[^;}"']*url\(\s*['"]?([^'")]+)['"]?\s*\)/gi;
  let m: RegExpExecArray | null;
  while ((m = re.exec(html)) !== null) {
    const abs = resolveUrl(m[1].trim(), baseUrl);
    if (abs && /^https?:\/\//i.test(abs)) out.push({ url: abs, alt: "" });
  }
  return out;
}

async function fetchHtml(url: string): Promise<string | null> {
  const ctrl = new AbortController();
  const timeout = setTimeout(() => ctrl.abort(), REQUEST_TIMEOUT_MS);
  try {
    const res = await fetch(url, {
      signal: ctrl.signal,
      redirect: "follow",
      headers: {
        "User-Agent": UA,
        Accept: "text/html,application/xhtml+xml",
        "Accept-Language": "en;q=0.9",
      },
    });
    if (!res.ok) return null;
    const ct = res.headers.get("content-type") ?? "";
    if (!ct.includes("html")) return null;
    const text = await res.text();
    return text.length > 1_500_000 ? text.slice(0, 1_500_000) : text;
  } catch {
    return null;
  } finally {
    clearTimeout(timeout);
  }
}

async function probeImage(url: string): Promise<boolean> {
  const ctrl = new AbortController();
  const timeout = setTimeout(() => ctrl.abort(), 4000);
  try {
    const res = await fetch(url, {
      method: "HEAD",
      signal: ctrl.signal,
      redirect: "follow",
      headers: { "User-Agent": UA },
    });
    if (!res.ok) return false;
    const ct = res.headers.get("content-type") ?? "";
    if (!ct.startsWith("image/")) return false;
    const len = Number(res.headers.get("content-length") ?? "0");
    // Must be ≥ 25KB to skip tiny logos served at homepage scale
    if (len > 0 && len < 25_000) return false;
    return true;
  } catch {
    return false;
  } finally {
    clearTimeout(timeout);
  }
}

async function processOne(row: Row): Promise<{ id: number; url: string | null }> {
  let website = row.website.trim();
  if (!/^https?:\/\//i.test(website)) website = "https://" + website;
  // Validate the website is parseable. Some DB rows hold phone numbers or
  // other garbage. Bail silently rather than throwing.
  try { new URL(website); } catch { return { id: row.id, url: null }; }

  // Pull HTML from homepage first; if no good candidate, try /about etc.
  const tried = new Set<string>();
  const baseUrl = website;

  for (const path of ["", ...FALLBACK_PATHS]) {
    let target: string;
    try {
      target = path ? new URL(path, baseUrl).toString() : baseUrl;
    } catch {
      continue;
    }
    if (tried.has(target)) continue;
    tried.add(target);

    const html = await fetchHtml(target);
    if (!html) continue;

    const candidates = [
      ...extractImages(html, target),
      ...extractBackgrounds(html, target).map((b) => ({ url: b.url, w: undefined, h: undefined, alt: "" })),
    ].filter((c) => !shouldSkip(c.url, c.alt));

    if (candidates.length === 0) continue;

    // Score and rank
    const ranked = candidates
      .map((c) => ({ ...c, score: scoreImage(c.url, c.w, c.h, c.alt) }))
      .sort((a, b) => b.score - a.score);

    // Walk ranked candidates, probe each — first reachable image ≥ 25KB wins.
    for (const c of ranked.slice(0, 8)) {
      if (c.score < 1) break;
      if (await probeImage(c.url)) return { id: row.id, url: c.url };
    }
  }

  return { id: row.id, url: null };
}

async function runPool<T, R>(
  items: T[],
  concurrency: number,
  worker: (item: T) => Promise<R>,
  onProgress?: (done: number, total: number, result: R) => void,
): Promise<void> {
  let cursor = 0;
  const total = items.length;
  async function lane() {
    while (cursor < total) {
      const i = cursor++;
      const r = await worker(items[i]);
      onProgress?.(cursor, total, r);
    }
  }
  await Promise.all(Array.from({ length: concurrency }, lane));
}

async function main() {
  const sql = postgres(process.env.DATABASE_URL!);

  const conditions: string[] = [
    "h.is_active = true",
    "h.website IS NOT NULL",
    "h.website != ''",
    // Only target hospitals where the current cover is an Unsplash fallback
    // (or NULL — none after v2 backfill, but safe).
    "(h.cover_image_url IS NULL OR h.cover_image_url LIKE '%images.unsplash.com%')",
  ];
  const whereSql = conditions.join(" AND ");
  const rows = ONLY_COUNTRY
    ? ((await sql.unsafe(
        `SELECT h.id, h.slug, h.website
         FROM hospitals h
         JOIN cities c ON c.id = h.city_id
         JOIN countries co ON co.id = c.country_id
         WHERE ${whereSql} AND co.slug = $1
         ORDER BY h.is_featured DESC NULLS LAST, h.rating DESC NULLS LAST, h.review_count DESC NULLS LAST
         LIMIT ${LIMIT}`,
        [ONLY_COUNTRY],
      )) as unknown as Row[])
    : ((await sql.unsafe(
        `SELECT h.id, h.slug, h.website
         FROM hospitals h
         WHERE ${whereSql}
         ORDER BY h.is_featured DESC NULLS LAST, h.rating DESC NULLS LAST, h.review_count DESC NULLS LAST
         LIMIT ${LIMIT}`,
      )) as unknown as Row[]);

  console.log(`queued ${rows.length} hospitals · concurrency=${CONCURRENCY}`);

  let found = 0;
  let updated = 0;
  const FLUSH_EVERY = 80;
  let pending: Array<{ id: number; url: string }> = [];

  async function flush() {
    if (pending.length === 0) return;
    const batch = pending;
    pending = [];
    const ids = batch.map((u) => u.id);
    const urls = batch.map((u) => u.url);
    try {
      await sql.unsafe(
        `UPDATE hospitals h
         SET cover_image_url = x.url, updated_at = now()
         FROM unnest($1::int[], $2::text[]) AS x(id, url)
         WHERE h.id = x.id`,
        [ids, urls],
      );
      updated += batch.length;
    } catch (e) {
      pending = [...batch, ...pending];
      console.warn(`flush failed, will retry: ${(e as Error).message}`);
    }
  }

  const flushInterval = setInterval(() => {
    void flush();
  }, 30_000);

  try {
    await runPool(rows, CONCURRENCY, processOne, (done, total, r) => {
      if (r.url) {
        found++;
        pending.push({ id: r.id, url: r.url });
      }
      if (done % 50 === 0 || done === total) {
        console.log(`[${done}/${total}] · ${found} real photos found · ${updated} flushed`);
      }
      if (pending.length >= FLUSH_EVERY) void flush();
    });
    await flush();
    await flush();
  } finally {
    clearInterval(flushInterval);
  }

  console.log(`\ndone. ${updated} real hospital photos written.`);
  await sql.end();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
